//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg5uRX4pvZYN2vaXkRYSTyD-RJT035CqpF_iZBWSS6n5aBy2jpYmmX4wiVj15qH0pb75QhFkNcliGPkzMscsyCCZjUWZ1seFPeSxkNLrci59_AKvj0t-InxA7Lm0bGp5WHp1BiqLqe3qEzoSys63XEHOECF92UOMHyjkHG4CPaC7E1_q8lY5i89_zdEPnI/s1600/homemade-babes-118.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am2'>👅Adoro quando você me deixa assumir o controle.🍌</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiwhJcGUqGx1DjYSAox36AQZtTkm77rqMYqQNTBk3LoM2PyEJjnN8ZpAr4aS_eVxojlavYR9u1hYxCMAhnTeX731ayODu1nBe9Ma1bV9zkOZylOqJ5_ou3zs3b0QSR2IGkRhAjaMBS6Izf0flgpDNmicf6YjRDElpgdYCwWVR_EXgFQke7CFoTh0wT2YDs/s1600/homemade-babes-119.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am3'>💋Adoro sentir seu corpo com a minha boca.🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjOJ-ikdYVtCyDvhBE4pvbHZjV9ntkBwWinBSVqZeBghPcLGCSWHDfS1cRECPrImYufjeIKsu_LI8o8wk5NnelO4YURGIzI5fAMkIQldj6CB-01q4suTh09v-oAt34UJzc-rwB_jjxtw275bbVg63MacbNE7GbeZOg3c2kLigepV4m6IKlUMYCzB2Tr5X0/s1600/homemade-babes-120.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am4'>😛Isso, me pega forte, adoro quando você faz me sentir no paraíso!🍠</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done