//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgC2w85cVTjeP9JKL3TeSGNZGdlFnsjiNwhXAbfuLB0ivZHRZ1t38DWLJRdBoOSZUSP1X6qjzOqeMrlnndzLc7FZPImbczn7TgNVxRF6W3hx0dIcauughayWBU0KSPTRv-4KwxyA2Uk17Ug-x7luQ23dURE5O6KTfCJM6kzyTuSGU9Iwad3oSgs8mZrp6w/s1600/homemade-babes-052.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>💞Muito fofo, mas vai me comer quando?🌹</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhpc15jwIQ1j_OsvX8E9lzzVFkSuLDHbbvKIlBB4kpKiMLToGms2GioVKKuAi3hq4eW5IO5aNP5gD0Zd9tu23e2hWKmdz4gywUK8cxqVJN3J9SZA_NK1CiLg9WvLNHUGAGnmU50OwD_smzWsGNMmI9vBhXliOXW5n3VYflMfV2LK0iFnhIsz4JG5u7WEJs/s1600/homemade-babes-053.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>😛De boba, eu só tenho a mão.💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjID6-x9jr2VOFnTpdhT65SD7ZfsKopZVhGsoXqCKTLg5i4RijIA5_apXVIIE53umwzTgCWcrEqUS-m1NjfKouVal2c61HiQEbu_qVAFugALFbgd1dL6XYfj9lTyngn9N_PIbQx6TSoB1Im9H3V7lqLyBNvtwzvjrIGvsEIzG1JzOauGhi7LYjnTx6IM0k/s1600/homemade-babes-054.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🐍Me beija, me morde e me faz perder o juízo.🤩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done