//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiwn0S7S7SQowq1-HlKPP_EuNWv-WQu-_gGcqQn5ms8zkNB-g1QiiOA9_Xi6A7Js58w9Na16vh3WHxmTpa13lSp0Vm3YiSeB9HXjlsq8hxQv5hJrnTT0sSlZnq6Jby0QvpXxdSHTtOzzJtvbrtAv0fVrQA2TFeIWUvDV8bOFiCv4N5toBvgDZYjQuVx-wo/s1600/homemade-babes-151.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am3'>🍆Você não é cachaça, mas vou mamar até as pernas ficarem bambas.💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgz4PWAsBgUw0KycreK8T3X650MFLBEVHoA4k8vC2RdLelCw3U99PLn3VexOJPD8QELyLMlEMdgw6c0kQfNUEZle_5xrpFt-HSk3DUeFJOtwjcM33KRIMOuAhNxeL4XFWvqtupavohobPvQZsqUk6E9g1jDvCBUoXpZlBWCfeUa9LnrooroLtlqsShmJBA/s1600/homemade-babes-152.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am4'>👅Vontade de sentir a sua língua entre as minhas pernas.🦋</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgS1dEV_37zfAb1ZAytVeObuWk0eWL2TJVZv5xVnJ_o7qWHiSf0lcur9ZotNsMu_SxADbKPBZME2Peb6tRjejFpgQauucuo4ubewJQpaIDInGwd6hQSh9h2kdXjuKyLfQQcgjgztLkWoKdoqpejhjm7crBcfFgs29fyj7oTXYB9aTvn119R1StrtlRFf24/s1600/homemade-babes-153.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am5'>😛Quero você assim como a linha quer a agulha: chupa e mete.🍆</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done