//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgP0cCr-pNrBtheQ1QJ3oJevWKXFMkMOAtuNZ4zXaxWUulMmB5rgTxl5ioX7FJyxlxX_tbrVNkqqalhxp1heRpsmYzsvTIVpf1fnLMFOnK1UHCxduIC_1Bx-FVDQm8ze5EsLYDcvH8WL0E5Qzk1WIWErfFPPeyvAqthqwOjC9m7C29PLSqOv9-2xfMaM4k/s1600/homemade-babes-022.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🥖Você é a minha falta de juízo!🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgL-tI5SODEUBdGM6697RS8JDoYFt2JwvRjaKVrVjwmqjT1wACf2dheqbTsVCJ2ZwupP1fY2bCaCxjKFmlIUzpMCTCjZyWqtuXQ78uLbWjC5MP8Qe1dMg-PIwJ3EegRFrDHYXA940qwvc0YkZw4c4AkjeDY7fqYDL58_BBHXR_qd1AiaJDWu_vNel1SoJE/s1600/homemade-babes-023.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am1'>🌽Vou realizar todas as suas fantasias...💣</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgfbC0xevc5yBBL_HTkO6L4AAjNesPcX-5fTSO0V4ldY87LtCnBz-AhD78jbswgCNAYRGOFN57xb-C3nD44CEhVTffbBFPGRABV-cpE30V9aKSCzT7yJ9kBVAhuBP3kQhhZyxcoIpPCOPpgKbWMUXV6Gvo8ji-QU_PKwp8BuUfe8ubdQ1U9YAfaT5uOoxQ/s1600/homemade-babes-024.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am2'>😛Minha língua vai te fazer ver estrelas.🤩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done