//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhJRfuKWwFj68hhkvh05RE0qVrY0ca-anikeLeo-bMa9_67xifZhPuEqN1S_Aywmler-DtnSLbbXH3UGqXSDy6ja1bVKjQhqZndSgv0RgFYwgtGjavGE35eFID2UiMwOZRCfHJ0KW9i9kVpRtpU59UJtOmmbW12nWuF-lTcKQkzXjdwKTueyvPH7q3wESo/s1600/homemade-babes-175.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am5'>😜Vem e perde o juízo comigo.🍯</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhtoS_g4U2XCuOJ1uJmVr0NntaJ8WZSuPAtVqu8AFnj5jA7DMTsZIbeHKX_JkD3oqB4SYC6HliBxOsSM0keNQh846LVS-1YfgBlB9NDi7nHNnMKaqnZNqDyd83LMLNf61Tc1gqC_uXeDVtV3LvOdvex4Rydx06DWMxuDO6JouriVDaEq1OLWmhc46RM6OE/s1600/homemade-babes-176.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🌭Prato do dia: eu!🍑</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhWerHB7j2l6fLjpn_txJtv0lKW1s_x1SqOOycvjcec5qK2rJMPqIBQ4nH21hExBM0JBxhm51v29GOT9lGvVNsEuEgZBBafL3BfMDvGf-5t0K-cLVrWkg4KTiPhyd88G3KvHg82PswG_l7J6h17Alj8vzwHs-SgHMlY7-KjUtMCFkVLRXG94Hc2tY1nDJw/s1600/homemade-babes-177.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>👅Só de pensar em você, já fico toda molhada.🦋</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done