//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjj_1f8SrV5gJct-EkxHKE5yLAsuUyoJJKjoaw6_o45cltKJURSCDd4vhXEoUAWYq3XCysrglhF7wALauFa9aRWSuKwunzUs2KYCHQ43G_mF-B1zXvp4w4CRMcAI6q6v6aZWDfMWwuHcUnW2hyphenhyphenXKJPXBGQ0IN1W_tNqTJZCNH6TrTkMUZpHYckIvUwx1GY/s1600/homemade-babes-097.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am1'>🚀Quero ver se hoje você vai dar conta de mim.🍒</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgtNIAMGTLUBoUPRAbIsYUlTTMot4Xsx4oQSVkStPf_H0szIJyKUMLSR4RsOFCA8ahuUMpR1vTvfWTF1CxhkAcRnC5_spVcCYuFJU2taweBPWSByNuY7QXvv_dNrSbrGYhyu-4F1yULDiQ62rBBrt8U7fgeIzvfDmN23PZzJVYtuc6Yfg634NyL0DpIQWk/s1600/homemade-babes-098.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am2'>💋Adoro quando você me pega de jeito!🌽</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjEhSecMXyi5jL0GImqRx7rJViZy_9wQgcMazmhaiQ2E8-jr6cZ9FN_wGVRRKBPdspG08LrAGVcqKJV9CNj_YqkCDueVZQDai4QW1065ZpSby60Ug3vluMdfhvZDao8mLEcaOdRamSoe4NCyJiJqVXJSOhJtHF4M5JFED_kuppSwDSASFV3K3d8KBksuwU/s1600/homemade-babes-099.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am3'>🍌Você não é sorvete, mas estou louca para te chupar.💦</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done