//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj0bB5b70gd_0lmjm05imFLn830EvXNEEbadOQzlTXK5VaSQYQ9JijtH94J7UnmNLKj7WkAF2pA3GgTmwpruRdfUHIn4XfYn3fdpYS6gfPsz5UMkvJpM2osEfBMH-v6Nf_1qd-35fWb_n4D6HfplyrmiGExJ6gn6azaJkuHbhzjX4SPNajmCNwJeg8yDvI/s1600/homemade-babes-091.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am5'>😜Vem e perde o juízo comigo.🍯</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjFqSbv8xxhGdOu6HZQs0AmsDwjfQsQpd1Zco3iJotbzMqWfaSvSHalQfwEUaS30x7cMX41Ub1EK9P9bQ7w2nB41-me-X3ttN9RdhKktholkJItiBx4rz2xoGHXM5mPaN8Iu3yFFG9NDi0ME1KJfHkZ2Us5tqBevrnd1vmRHj5IJUKxm99Wkh5p1dyfjOE/s1600/homemade-babes-092.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🌭Prato do dia: eu!🍑</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhXDtLHbmFI8dtgL03k2N9DYROdg14fTo7jp3xB5XFqv96gSgDAcjbrMDM-yAU9sY7tAx9f4OwM9aWwSa0RtpK2uoznXgCiId62f1wdCcoRo5J0TPD349o27iqWE0aqIjwY2A3XJ3JEY1hFB-Hq7dTd6EppN3FCa2U_TCIUyIIpOujH7dU04kk3hjOwUHE/s1600/homemade-babes-093.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>👅Só de pensar em você, já fico toda molhada.🦋</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done