//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEir7yDF-OTC4VfnxUTti2tVgkFyoZEcpv_UY5nFAbhVIeBbAnH6IRht2Ojh6TJwob2LYNwjpqUIAB61HRERyALhVy91pEZOVYdTGFRxW4mXexllvKZstBWlybZWIlZ-e3zFd7ltLEFTLiHJI0gSTClIua1TjRtGuGj3FIG3ikBgC3Ue8-ICNbI4H0c-9JI/s1600/homemade-babes-217.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am5'>😜Vem e perde o juízo comigo.🍯</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg8ltGFSdf-IGlD8KDQJKiATdRpYGvxWV2z2zxoNdPW6uykiIUXGgJJBdutAmodh19ywcLavxqp_ylk6GZQ-iDdwsp-w2LLyf7HM98wDIhuniJxcgJZ3vuDoQGLccWFwulH8o_qqU8SF-EptM5-Fvp24KMUYE9Yu_4PZfbvvnk-OCOfLYhHqXH6VBi_ZPk/s1600/homemade-babes-218.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🌭Prato do dia: eu!🍑</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhg24tDZ20iuHVh30dczwWQNz1AtDuY69ynf1DBNlx-OjA1saaBew4DsWGQ3QiWVoCDRAqkpq_5hKFNMjWI1WSecise-CpcoOkVrc00khrQFOd_FcyQuYh2Jk5CY4RKexwiMHUo4pVvDupGUtyjtgx69fzYCa3TWFwyLCPp4U0shxfXbdaChR9nKz4FGqg/s1600/homemade-babes-219.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>👅Só de pensar em você, já fico toda molhada.🦋</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done