//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhmjCCfWrB_k1lodseBX6NNQFQZvAX63xlZ3VTXuiEHFLuI092AYJbEQbJzFAsk7uDBmaXjHlG49SMFh-ohsEcjuzi4XzQHXor46R7OL7n4InDflmdkgXKzzO-2SBAdKHLU6uUU6XR0ppiwoCJpD4xO2KJ56XmxSz-l0fXA5OtYYVqMkmi9q_EjXF1ZRs8/s1600/homemade-babes-070.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🍆Só para quando eu mandar.🚀</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh1o5xpNxKtx0kRVAUQGAyEacVxhp503xq_saCMj_VUi0gDwX-BqzRGN4asrsUFovP49ryAJI3viPNM10PoBHrkaZUuHVpHRfV7m9P91G59fxaxWJp6WF0I62uG1OEjKIgE4PORGNJrpim7LUQQtTWdk5FDi2FSYRA559eiLYt6NcgeVyLGKPgj_SYjbZs/s1600/homemade-babes-071.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>🐍Eu amo o jeito como você me fode...💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEijM5vvxWkOzFb_-c7rMoKaw7e0olgDs7yV8pfjP8MKCiZ10eMT374mBdoH1BnnJI4K2DgQBCVEd7qzFWc0YGTXzmaWCZBNjnabn0pNkbdlpc2_OD3MyB-lhVPGSd4u8SUYRU8fw0Yq44Xdi8_1FAenOZzlw4TjUGkuB8sXE5ATv6ppQmbIQD70C9S1KWA/s1600/homemade-babes-072.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>🍆Me come gostoso...vai!🌺</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done