//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMD8DhVDbYMeMjrhl6lp9GaL0q8LRX1e1AlNJRsMgTT8Keq1jrR7mQ70ZsReDNQ4PHKeqcCtVhnFL-w-V42iWRf9h6lEQFLqY5iP31PNNPsvTMzpWykNMX4rIWBuLoHGpy8KK9DNn7mcjXT03UgfhiS8yM6l8CzV1IWG0NmLk4UqxDGxcmW3nh9sX_KL0/s1600/homemade-babes-016.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am4'>🐍Pede com carinho que eu faço tudo do jeitinho que você deseja.⭕️4</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhbJGI_Jg3J78oD36Q-mevi0lqayGq74w2X_I4pKJTH1_RhWsf1ztErZUiDn9YmD6hueL8w3yhoIrl8Iyb5FchTZ3743HF6ylaYg5eL9JCqMTRof1tSyXG1GsYK-DxuKpb9WLfk3d5nHoYRAcnGeumll-l-4k1vsdNg51RTzkVbmXcyOTOl5JVoIUzzPF8/s1600/homemade-babes-017.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am5'>🌶Só se faz de santa, mas eu sei que você é safada!😜</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgQXBu2ltyA5dAQsbyayTx-Us8Ry7IG7OUg7dV4olyUjzE2wiOYaDe0yc5RN3FcNENGfbvxclNLmlIGjsLXmayhzDJsQcKlJTTw1UppP7HG-GtiJmTNAO0CTTqheiG24DptwLM_pk9BeMlQIQ2WIBNdrjBcXnPIWur-c7s1PwUdx2ogN_9MGubqxkNzaZ0/s1600/homemade-babes-018.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🍆Eu sou toda sua, então faça o que quiser comigo.🤩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done