//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjOkcbqjUJ380APpCJuqn6ozORe_t-mwXLD39rzbrwcvPKwji5HFa1b4by7P3_eY-TXOpYkNa9Drfu3AP0ug4cdFtTaVWbSjFsRJcKO4s0zVFE8PlwkEUOYMUHtGFjLlk2qlcI8XvlX5YOmBPfdO9cu1IAVu0YVljxZNQXqEN-neZ2xLSz_W6uPg4TcpsE/s1600/homemade-babes-142.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am4'>🐍Pede com carinho que eu faço tudo do jeitinho que você deseja.⭕️4</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjLxvAUre6o_sp2kj04Msr3Eugt-gs2XO8HkW0eqB6sGu8mySl9YwjEIgD-Il0y7zBzygxpyfUdmVVV4HsozRLbATZxxASFHMW6XGVk4U3lzC62zkjCG9OFfD5Ww-XkUbx4rXye1jpkW-M-zAYZU9aT_o3Q44AkQ0AfsikyoI0YvcxDbcUKZpFAU_mJ9kI/s1600/homemade-babes-143.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am5'>🌶Só se faz de santa, mas eu sei que você é safada!😜</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgxLl3sJ0Yyo1eCo2dG4y1SVwQICFHBDIgMrtT9vmJr7j99qgvr70x6OU4sLgrabNByQUWii2abh_kpPJAq6SkoPNH2nmqse_bTHc2-nW0f2xHXVHzUDgEbYO2DUpq6tYdkMgMWEsetkDEBVP9iX8YapihFH5zd6HOz3zYgaU1JjtGaKJTKtRMMvQuA4ug/s1600/homemade-babes-144.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🍆Eu sou toda sua, então faça o que quiser comigo.🤩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done