//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiJEKbJbrEdtLsWdpRqN2ixZXL86OvxasbrVStbk-Kr7tDgH9e8jdXf-xyb0kFb1qgx7UThUTIIzyVYuOeu3c1wzsFJTcNMAhRnf2ARS9QQ78Ap-HttgoPwvptopiblV8XE-72n4hgs9DwpikC1HJsrwFL7xCChaC5amxtZ-aP7zJbnTv2LrTI9hY3HE5E/s1600/homemade-babes-133.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am5'>😜Vem e perde o juízo comigo.🍯</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjDsyj4VFNrOa3t7DDFnRcy8ITkGy4Z025Hrwdj5IKLTE4otazeJrBOXJH9RTGIr9FSGsyn_nz6ldv13RpODfsraal0MAO99i1aqfN6yNQsghAZXDb3e74Z-5GlsBymTTrDHVkCDZS6mpqeshUX28ndNOMylZ4-AQo5djBzrXCTkujOZVerg6X_T5MefvM/s1600/homemade-babes-134.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🌭Prato do dia: eu!🍑</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjh4RFetEudQFFv4R0hyphenhyphenIdpIDqEbR9X9in5hmc-eel73Vw2igzNbT8jW0hDgCol7SSWBCNxt2jqw1jKq6POa6yFqsvuNUugmEKvGZ2JORIEbgXkq23U_E5USFePSoDBgLIjFx_ATWRoZkGX9GOhoTSaExTvbOH0isIXye58xHUjmmSGe8vOnqKf-7oOsdE/s1600/homemade-babes-135.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>👅Só de pensar em você, já fico toda molhada.🦋</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done