//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhuNr3AGMrrQT-poyUFBhHPW95L2cArl6LeUTJAcHdEEJ7N2YRRaxA0KdU9yG-jNIazWRtKyZc7CRjyP3DZFNbbybEVYRbojcUgl7C8DYpY12MRSftQaB2-eR5e32qCSa26_JLj8TPNn7pib25pT2hpLkmFV72ZuR7nO0djkHZKbu4SQG0v10OROCNpNc4/s1600/homemade-babes-214.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am2'>👅Eu e minha língua queremos saborear você sem pressa.🍌</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiUfU4wu8_CQ-Lc_fJAcDNPZbsDQa8EW2czRPcOvtdZHPGMWIUqAYmrxmhyphenhyphenQwJB5tz49vpcGGAzEJxOwlurwFUuv8o6nWoHZKyQf22nAORz8_HStIvGdzitZSPZWS_Jbop7xcpns237RtugIIRQPuL3h5iYOfJ6an2zjsEautTjdoazuODhyphenhyphen_VUZXEHjxE/s1600/homemade-babes-215.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am3'>💋O que você quer que eu faça com você hoje à noite?🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhK8fNBw5EJXahX7SRePfcsWWN4rNUNpbfDQqy2NJUydhUE5hnnGUQuLSevdQQnRXRlKzeJpXijWM1pJjJq171r1SevJYlErhY4q9WwKHoHjcHFnM0pFEq9f8vaIa1sHFfa8UkM7G2xQutbHOuUB3-do4KgiE70lb75ysbVNwMgU9HIVuc2EM9Xy75mRPo/s1600/homemade-babes-216.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am4'>😛Me leva pro teu quarto que eu te levo pro céu.🍠</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done