//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhsVHCz_rA4QkxSmitLU3FpIez8OAVzWkNbnLPdQOt4tiWGk4Fr1ZQltuVCR84xHPhSYPWW4NAdxa87Ate8SOsKg-qANSBkfMZJuUfs3tpMRBrt320qr16pAn0Iw_B4vdyMTqstUR9kv8HOD_lIq1KRoqmu86j95iZRKcWsexDuC8FL6p-1CGAq4t1MejI/s1600/homemade-babes-130.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am2'>👅Eu e minha língua queremos saborear você sem pressa.🍌</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg2_iRukYHpehNMom_XesbJElTMrcnm-S8ZHWi8RDa83z3lLkmeor6N-YtfZKcRvxSl77h5oNtY5lblJ0yviIPHK8tkTV4XCoDrlt45N0KYD3_zqGF27FvaTsZpoftY52QWRGLEi5QdtMVpyKprV480Qfdra9Vft2RtC_lpntvVdrpnxmExi0PFAhp_twQ/s1600/homemade-babes-131.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am3'>💋O que você quer que eu faça com você hoje à noite?🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgMeC03VNaZPvrM7gnG4vrSfagT7tMGK8Cd7u5wS33WZUXnnGkvbQKjLb5GzFBjUiVBBhvWAXS4AbWpydBexxh4zu_NRoei2FLVbo4VP2YcBR5X_pYiN2RjIobnGu1nZg7pH5O4XvjSmi8B7pLr8xkqhVa2aBh15a_UypAovzShFzfDUfYlL0eLv-ZwRkE/s1600/homemade-babes-132.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am4'>😛Me leva pro teu quarto que eu te levo pro céu.🍠</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done