//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj-rrtuZ-9fBcrclNpS6-pUauekRiYRzxbL6gE_utjz_a_cpezYHr20b3egt0EDqpRhFVjXBJtxY7np95S4XxLmPBMPUb0R3fm6lpDAJp6weer7z8V9W-qTWUW4ZDXTSk2x5UGBhit3yVMVxCq-hI0PFvI3H8-VhHDwLGI4pD9q7gkcS4KAlY16166N4x8/s1600/homemade-babes-124.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>🍆Preciso de você dentro de mim agora.🦋</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjpHeCMM3vWRbVWhwUBlLLTQYzsBT3il-9_6SV2CTqid_rH2t4roUsIGwVsHeSXWAsEmEJuRp-Etcwpt56pOv8ifa_qDuyHlxKqNY30oYPZO7rRSfwzp_Ut_7lO8ZyeN0jz13PSUVXKWhTIEtZTEFSghr3BkRL8s2MUloO5uT53bdAPHv3mxSQaYpwIfPw/s1600/homemade-babes-125.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>🐍Adoro quando você me domina.🍩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgDhsxtu8mr__fZFwtXMuZ-6Ifglcb302ALl2Fs-Vqs6sch-Iq4tc-wG5VZVdoOQfAjWA0YOHB6lV8HZa8w9075FHVir2a3HcUJ1HGARmsQXFo8TZkW3plxiSOkbqiQ2MI2IZUOdhDfoLVSOU5y__UcVI3azmDcfSSRqQF0JOqkkvwq3Y3KHRdCtanWaX4/s1600/homemade-babes-126.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🐍Delícia, assim, muito bom, gostoso…🍩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done