//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj3qfFFy-6SSRb4tME93njHrTrLHP5tP_RDZpcPbwk31F7zOeYWUBpRJHQjVIyPxUnhVBwHtJ_GretVqvEUm9AVo7Z_KfXR0HBIOQRXD8jgDQxb6kn5rwkJ5s5QAW7cePcmriYMpOTiPJILIthKQnDnnC9siPFQTa4eI8zZtDZjqmTSboDk_Z2nc8QvCtM/s1600/homemade-babes-199.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>💖Adoro quando você me pega nessa posição.🔥</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhC_u6zm7xLCegKiiyJWUza2LKukNi3hjtOS9BUS0EpcMkn4RxK_nfxID_iygQTsQnG-iUhZDHBnDlXB_r-gyMZ1yOBOboLImVKo_Sd3wPCSpRffovKoVpi_iGp01LDJs1mluG2VlxBHwwi7MsSp8OPTjiMTEZTJyNJahyuwUV_EQepuJwrV9ruVRNHSOo/s1600/homemade-babes-200.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🌺Delícia, assim, muito bom, gostoso…🍆</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhQ4n06JqbI_NDSVYWcC1uo639PUfcMrLBaLt_-Uv98bcOP2JjySMBsseXIphq8R1q6zzgojTU_gog9navr8wyOZZLTuvWh52iTmxc-_zFV4ECSSOL56F488fIaGUJZZPojTGovJJWDUXDxGlMn7fm6i1AsZCCdsjvo_NZhox2gApkpsuN-vcp4XJ1w76E/s1600/homemade-babes-201.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am1'>🦋Quero gozar com você.🐍</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done