//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiXC6DdEXKtwoHuc2_mKgCtBBGGye5iTPJDGIjZuAnXXE7SCdozjFJz5-XoJc1zM5Hbqo80aC-XVE0dX6ids7S5eJSmD-Kt5Z8aG9gfe0VTnPV5-eujMGUtX7VUfTs9cEF9aoHh2E-hxV431ocDSMCZsnsLkU2C175xTDgY05EHPl56lS2odXac6w9YhfM/s1600/homemade-babes-058.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am4'>🐍Pede com carinho que eu faço tudo do jeitinho que você deseja.⭕️4</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi7_jaBer4R3IvMTbjnU6y3uYsHTdTYrSHgKHZwe09Kn1TCNc62XDY2JMQf-JdprAQxzNzdAS1UDQUY-bG9i1yrbbYhp95VdD5a7i_cR_ktWwM-CzMrWYeCkt476vbbyTKJuo6Zs9ojPWXYW7QoNFTLlXNhUqMJkayQCeXB8Xw1cg2LXI9KFP3mByT0kj4/s1600/homemade-babes-059.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am5'>🌶Só se faz de santa, mas eu sei que você é safada!😜</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh9M6BRNvUEJqO5OdejpSekCiIrAwcCHi8G9IMOlvOiqMKgX7tsLrD8SfIDToHwd5apGCBYxtsgcMMYxhBDKgkpnEXOjkEEX5RgDZyyZYgFjgeK3nLH-jIKxGww5027bV8_A2H1cVUN3K86uFrCUt8-S8l50o7V3cx43hr9276F7k_VmzP0IDl-Ny-jjgk/s1600/homemade-babes-060.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🍆Eu sou toda sua, então faça o que quiser comigo.🤩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done