//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjCHCjPI_ER-mxZ4tM7B9z5g-PLvvM8QfbpQtmYVpBAU10eaZsLF2TnMqa1rvv8dZJs_Ck8rxK6SocdB640N4lJprtmsAMvVtJ-GLVnur6BeV1x_wcx-RuFMXUnPxN0oisnVRoJ68WkArb9vg9jO_d1kQ1wA7oDxNjiGSNroRGnX9gPtaKOCsV_ZUsKUdQ/s1600/homemade-babes-127.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>💖Você me provoca, me excita e me deixa louca!🔥</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi4PMnK0nF93BeKHvRrwCMXD8rcZjMhurMs352iYhXRByOYJ5nNJOrEQBTalj7OPPALYppo7cSNtGQ9CjrYaiC0WB_DXXYmOlUW9G0kEJWsNlFPFeER6BW3BkJ2py9MK6BDrIimhbe_jX7R39EJNhyIRNVd2-rHzONDIfkkHcEZddrg9cBDRRzAs1VxLpo/s1600/homemade-babes-128.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🌺Há algo que eu preferia estar fazendo com você agora...🍆</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjSnbJzNvLf-hqP5pIBr877ZJyyqcj8bcywB_8wC4NgTlhMJVaF23OejLvrb-JKdH_YHzlEh2f2eUxVqQnNwdUHL7jpISbqulOAHyitlx_jttyLkKSgVnV5ikERS56MVAHvMSnHBO7kpfySyPbpGmDjidr_U3JUg6Zk2k2o3BKUKTHIHiL_20W6cfLBtck/s1600/homemade-babes-129.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am1'>🦋Me mata de prazer, antes que eu morra de tesão!🐍</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done