//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiO8DYDMk3K6OUoc2J5Adb96kL4uJO50ih6ccu0pKOPn_nZnQXXVNXXttabUymsQOWAnpfxn369kgzhEzVbhFAuk_WSRimENtT3mpHu5iIT67WSOBLIMtIoXp2MxmDaAoUPWjhErgucnj6LhLzqnTZHBC_75rT8mFY-Oe5p31UrFwZe5080EJZsp5JfsE8/s1600/homemade-babes-184.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am4'>🐍Pede com carinho que eu faço tudo do jeitinho que você deseja.⭕️4</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgERzzz0BuLn1STrxKUzCDzelwKyJ840DjiUjuFUOpTG_x7sJbxFI87vuHy8ODFO2Dxyu5FuqlbhCNnT2nzv9Rve8K-0rv1oXOJjBaRoz4TLz5UCD18dUf31OovD9jDAs4TxsvO8eOTPIlyrlis1nMvt-TY5of0XFRIiOkXCuwm1eKDDTJrXd0uZRWkhSU/s1600/homemade-babes-185.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am5'>🌶Só se faz de santa, mas eu sei que você é safada!😜</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg46fJVU14TZSVBMveuVse7i6UGBdNII-Emd3xL9GepMUsjD2qE8zSEHzWT94eQuF6_Uisf58bvjjTmA3AjGMoVaGZWFnLZflFay48YdEUBnfEvUu7zpOse-BSPjWNV5nGpphm4UA0So8CDfEWwZKv6C4pD6REuZ6druhJ_HVQUpR7noyrOXo0PT1A0RnE/s1600/homemade-babes-186.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🍆Eu sou toda sua, então faça o que quiser comigo.🤩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done