//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhAx3t8Q9CuloT425hOtV3_GxsTXCovQ1-EsjBxrHaVbI61isnPegxmXh_SkmtFXr-NW92NENCQdERwZj9EM7RHikr95XZAWxU6qu_sxSqtgBXw0Axo0CNloKqLCf1hiF4GupIZWdLZvlpxRurpvep0rBhW13m7_pl0hAjZm7RFe1oaqhN5F-npy5TfoAE/s1600/homemade-babes-115.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>💖Adoro quando você me pega nessa posição.🔥</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiXlZUytrDjLJji0rIwaD_RvbAqxF-F_ZqhyHT5oCRDVdJCCqZfJNiYXhhyMTXJYD4vrKSsolRjS4dFe0UHXs72Xf9d5f2QR3g2nPEUWNaDa89N0wWqiCNCXP3lJfXzjgGu4Ud57V5jHrEHcbY-J1Ry1rZIcBR8iECWfZAtW9MjyoguwkcRjb4foOv4n-w/s1600/homemade-babes-116.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🌺Delícia, assim, muito bom, gostoso…🍆</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhB49E-uFJgK0bIVHkrvOO4H_5Zf-IbITku-hs0g4NRN6zO3OlXzQ-YKMuji9s1n9KuAExu-gT3JOGrUrlI8S5833sWmmFfEI9wTHDaTQAVC_gMU6YbA9hoyowbYpFeuJSyuv52Vn5EU_73jRCC8-YXP81ORJLQRPJs1_yEmSkU3DpeG8Rrq3ZXKaARZ88/s1600/homemade-babes-117.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am1'>🦋Quero gozar com você.🐍</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done