//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiWF2o9bdL3upMhW0g5ls36OOrnhb80_wa6VNs_pGz4UItrsa_Piji-EbAmMFi7UjFlGAjX_B7fqIrQRhRzGJS2Ar6Wq2KpBYrjTRdoGHj-8vrv5iQGS6gkrHgDdi3nver7hgFJSvDa305k3zF_ai4a8P8h6Y7ei2ikM7AaiX2TSJomM1yxEtVgLgPzCIo/s1600/homemade-babes-043.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>💖Você me provoca, me excita e me deixa louca!🔥</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiZLPLKencrFo9vlGgzuKqzLp5oR_nc8UYnVxcSvKIhswcNc5stebEru4Gsp9i97vkFP5IwRs_EcZvxPEexmDPeAiKb8BT15bmlMENkBvH5XQqNnqIir9mB7-icEUQCHC6gBFue987C-UrHd0LXiLw8Xs8CTpro5Nb1fJrr3eS2842F55NEIM3Aas1KKCY/s1600/homemade-babes-044.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🌺Há algo que eu preferia estar fazendo com você agora...🍆</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiLVPdqUul50eZGlEuJ1xfDSwoCkChXidpMb5Md1bCGEYlzGH-KGS9JyTkGBkz3WhgsjyA3FKOup0RzDTz0QqdNNHCmomJTlJoXyEmKU2RzdL_bwvdttF1uGsiQs4i5dwq-x4fDyzE3us0RkURtHo-1f74KdVy94_jTGhVPDNDGwfiirqxRi7zvBxkgMag/s1600/homemade-babes-045.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am1'>🦋Me mata de prazer, antes que eu morra de tesão!🐍</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done