//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiikTBdxLoLkUn3bfcX7lte9os3VCgbSm6qzjq9ehpVTNtwmFEf-tdv1Tgj6a-ID2Yzr1il4KAQh6FLsBhSqkAQPrKh_Zb3X85njdjIx40zy7PX4rG9PmcSu7RUzvTWyqqBZyR6cyt92VHL539v2iAyfx7LYkYgofOcn1Gs6L0HMA-tmsCZSCSdpWn1bXY/s1600/homemade-babes-154.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🍆Só para quando eu mandar.🚀</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhFLj9D1vjRx_4bK1nC_T3ORdA74ua-0Fhou0bdaWLOFlviPXpAVg2itiu98nEO-M29KrkBTwJLXWgaacp3Gfpf9jCDDvBPILgxMd7LhzM0WrGV3J4uA2lMqq6Fwt539DaVBRtED_Nxaj0SE0ZxO_BGIMGYsMx6IqTWIsdc1rIOkmKKGCbjQa1BcE_ecQs/s1600/homemade-babes-155.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>🐍Eu amo o jeito como você me fode...💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjV9T_uRxz6DE-tpbrozEuSVeJlBdZyWmQkv8fcDu1btaTaY-WCdIZZJZJqWEgl3qtay1__5ifGF55_0Im2NLmun4DmdLCBSujDYNrSUzrQ7MBBuEZTeDddgnfjRSxwnlYhjU1UsqrQumXeZ8nqvCUqKatcT2jEbjpEqp84-6maVY_RH6MDAl2e6HtWho8/s1600/homemade-babes-156.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>🍆Me come gostoso...vai!🌺</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done