//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiLP-rlKqcyRJ7_hnOc3gmF7wcDh8iW40wTFS1T7Ygme_jDBAITZTEXKVtgcv1bMPii7h0qgplZSs_mChZSZHvaVNYoU2pmeUmZA6ws0s0qJ7qd_cW_xutAz2MhwPi1bkzv0vwaXbbCD6UP9pJ8u5J6_tosR-hadYE2DbIEeGC3dPEktnVo7ON2WZXelC4/s1600/homemade-babes-088.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am2'>👅Eu e minha língua queremos saborear você sem pressa.🍌</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg2mL6BPAjqzXyF6T-JDS71AhA4tXvv1DvHczz6rGvN5475AyzARJ8rY3Ijgak5D_0zSfubnvy7UKr3gO87Xk2VzO7DvKpTGkFyYoObuP0eb5teXAlPSXdXhW1uXkjnPwSd4Ayp_RXiVfCk_NlCN3j-YOUFWWa82zy5xsSzQnL9ZFHahH0jV_OBTyPwXDg/s1600/homemade-babes-089.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am3'>💋O que você quer que eu faça com você hoje à noite?🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh4vPkt0kDI99EQkozneM2Xd7P0L_hhwbQMo58NmiJi5oLGfRfgSd69K2A5BPcm4bQRsoT93bXvs2mEaCLYhPhL5tx8umk72a-o7-jv2sa9yEjN5FTfvRqh1RrspzDVbD8nLiJti_YEopOtiqIb8dLh1uEeVQPdIxMOtWAjuCKVtMqDyBT6Bvckmrcn4dg/s1600/homemade-babes-090.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am4'>😛Me leva pro teu quarto que eu te levo pro céu.🍠</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done