//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiM-7bjkU3eKM5wEXCNm6GTMz6zYKyzdpjo3_YQ8LQD4BDXYz4Abm3P-X9D7DPPh8IZIXKZBCV-6GD7t-af76yItPtiGhWWzW6iGHqVYdbvuDRahcw-zsMrzRxCePYHELUHwmJT5ESlVdlRzV2oeRaqzOdGsaUWfVEJ9LdQMrAcWq4YrCyRbc-sz1ZHJv4/s1600/homemade-babes-220.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>💞Muito fofo, mas vai me comer quando?🌹</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiNRV8DA0zH868zwdYmnFq6QwDXFp0Zaix30FfAwxoDFFybkhTW2VmswmVyIG4vp-VvXemdAaHao757uy2uEbV4MxnEHR5HGiIlvmm3r4AiCvaqiWTw1JeYfjWZzX-Ke98a-wMQgSEl2lOchtHCvQSKjfH-HLtPIWkGzV8BRQNXYHgsZw8ps3WQFonRHBs/s1600/homemade-babes-221.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>😛De boba, eu só tenho a mão.💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgNkCizMEKkyCOz8gKQFvMPli8f0yAm2L8sZ7J5h1GCTOtX59xzihNF6Xr_hp9YscKHMfj8q1Ft9f0UB5Ck9Ev5kcFnFkcU7fGP2qqLDSY3iXYO3-BBGVwuSiCgYA0Uc8wz_JA8LvSA0XxssmyMRekTsJ6lcrWxdCix71eS2T367IE7kUEFGObhmk1pyww/s1600/homemade-babes-222.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🐍Me beija, me morde e me faz perder o juízo.🤩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done