//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjElyiMTxah8Ej-AgsYEAbG-iHS0_OSjIQ3vpM7EpR2AXvkMrlfSlIlD3L6OsFAg54e9f0DQFyDoydHCDWITXPHX-zxXYh-saHgSXzL_ayuKtUyg4R66h1XBzDlY6b2aiEsbRDXkVWzh45Jdq7vGJTsZKLL-opFqTGw1nEwLz6H-CUwNY-q3lhuEXQxpeE/s1600/homemade-babes-169.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>💖Você me provoca, me excita e me deixa louca!🔥</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgs9HdMquyw0rFd2icSNAFXaSq6YAZotP6O9VsCyzq20uvS2nmjvNWQCbVFDVdwuu4Fn6M7K4uH7hGJhgtJ2UogWKA3NnzErxo0oELk8S26kQKxI3lv0RYLp-ue5H1vtwhyKjhUlMxVqL8x1HWugBC4REFpiNenc3cYM1wsFoX-UEM-rn2h3bgVStfMoiY/s1600/homemade-babes-170.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🌺Há algo que eu preferia estar fazendo com você agora...🍆</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjf4uPBx4qC193hrduX8RodHzmaK2vhcooWf9nEbInlBBN-hZ3NfHHeJ-FNHOC5SugIu74eDwYI9jkTTG38yLuxjjDuqlWnnVUEkYQoIPnpX3XzHw2Ga0DM-LLhZsMkL2yxvTTC4ssub0QkmvoWR01NuRQRVGTydPLMuAp03f1wt1Eqjb-F8RKa1CpwOZ4/s1600/homemade-babes-171.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am1'>🦋Me mata de prazer, antes que eu morra de tesão!🐍</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done