//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgxVPOtM3liWr6e_1bwgBgDAt05PfBeIe2eNnCy8_QPISzBHVSvfp9igWTuiKML_Gv3DR0oLZoEJ7ZC58kpvuHEUlq8NwdZDHE3RVnQOIPaB0sz2IoxvUIPpR0piUqvkyBiLCLR2AScoQd_GI2fHmhozsN1-EUfyzlM7OxnYFDFwSS6-mqqAulKmR8i8g4/s1600/homemade-babes-187.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>💋Adoro sentir o seu corpo com a minha boca.💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEggGbkN9NPdlEoFpjTOZCxqqFgBeylfjN8xQmi_hVi-mJJWMwqZidEsup8wEoh4yZm1ov9lpaOqk4NBcwmIeO3e18ZjHKVljwL1fuVj1c5fx98Pn-lFbJ90atF_a1xkzZxXk4PNinOEYvuee8N5z4XYAhmnr3HbTK0Ph834sn7dM1qPc7TAvYu6CupMdBE/s1600/homemade-babes-188.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>🍩Quero que me vire do avesso!🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhbIL4N83D3CupCzqTovNVF6gHe0qxTxuS8T3Zj9jJlkGJXrGDmPXjfIa-43QsiKwQRX1tmUiZ6-qnlA2d09eiljSjwrfri8lYWWkIgokPq_PTO63I4NVj8SCCA66ug18Gm-hbQxzQjuc7_BruuGzAcOd7F4xlu2yp39jdOGbt_2u4-nERnUxYJjUIW9DU/s1600/homemade-babes-189.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>🍆Hoje eu sou toda sua, faz comigo o que você quiser!💦</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done