//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhV1JbUwbOv6Om61ZXRQTQAArCKRh9yCam7SSdV2EGdqy6kgBjcA9DcPgrylx4mxrBCQHp0lRl2UkhyGWoBh6CdoZ8WLMTRGz_QFBvapRC-bY5dNJ4FASLpKGBu2Fk3iakHfXd8I5CJzAFvI2Ae-tzkSDn4suMF_8kFxSaKDAgA0PZuFpw5ozHi91y5ZTA/s1600/homemade-babes-085.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>💖Você me provoca, me excita e me deixa louca!🔥</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhwDx5KOQ9W9iNSX6JtHD5AvHnyiSoTvXZi9R-ZBrVzIyD8FdnSkhW8YAU6uPZ_hzrkbX1dMwkgJbap5ggh5rIK4TxVWOfGUJYKdB7U1EovrvM4usm7hUOeLYlXTLtBf5iCC_bXkXFsbuE-sFZibAS471AFN8bw-6z0ODVTig-j0J7ZbSBCXw7yliQ2MV0/s1600/homemade-babes-086.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🌺Há algo que eu preferia estar fazendo com você agora...🍆</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgIlCm15yukkMgas3fRtlCCBDSmu2ljwe3-m6l5eXseZZbLjqRm0xquCt9PF8P6BLPMFFZInaKpn_A0AKckBE3v0f3tRqzkyG63B5eraczbZv1t8Ho01WUColHgsnxsPyPTKsWNdmConB6uU2fZL27ZqUfowZQEZVgO1af-LgEF7DWI_TKazrxmSPhJf4k/s1600/homemade-babes-087.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am1'>🦋Me mata de prazer, antes que eu morra de tesão!🐍</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done