//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjA3o3iiKHETkzQ-eM_JDk4g24eA3zNpkYdQUv_78vLEgyS4u-EbM8Xzpasw1PGe1ryiPhfKYtsRfRg2v6wiGIPOun7x_hLO1wn2BcbCFkVi1BJzC2QwvYQiGIbk0SvbL5CyLtSXB3xCXfOLjCS0lrSK_76Rxb-7lH-UjKqY95RxnqBmJw5dp7DyJ8jJF0/s1600/homemade-babes-178.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>💞Muito fofo, mas vai me comer quando?🌹</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhtvwrEWJOTPekK_-9MCTtPQkJQC-BDOrezqmqVX7Bv2evPtcMOpzW84m60wowzBCL5nWD4Tu_8KFwXcJbDjBIwZgtiDMRCVcWIMT354b9zfNkXFd3uGf3rYy9ByqEzHk64ny9MybJ8iRJm5AzTlOcjqDaViLyyDBu4gzOEckDly5S8WjgCZ2cwXA79yJ4/s1600/homemade-babes-179.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>😛De boba, eu só tenho a mão.💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgvG3gi6-2U_2cVkppfwDqDlkAtyqvLCtSxGjVIx0gdIox0kJePWUSjFnhhR7slzrHHqku8N3qAm_MVkGmv3PaTAVE2uQ2jYNpj5aomVdWFE3ktAYB-n1_BQ0QKVwNPf12i94EEUOPD9BkREw9WIbLINmyYHLiOHMo21RWEFbimQ0wimib45QaiEs08QVU/s1600/homemade-babes-180.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🐍Me beija, me morde e me faz perder o juízo.🤩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done