//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhXpWf83i2Z-pg_xrchK7YThkvCNhepzVRECi3ZHe0o57A4tX-tjGGeI5PYxVYc3frFvzXrBgYsuTZwx5dZ16lk9nyHBDXOhjsZM3WVJWONBkFKjgEHGfvwUSuBJwldSIrlnzBi2LeDij66dwCCb9w3NuISonV7XJ36UwtwZaLfZaonTKkiUfDX8Ia8CL4/s1600/homemade-babes-034.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am2'>👅Adoro quando você me deixa assumir o controle.🍌</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiw092VjslmudLYr4M_D3Z2FwAcA093KHhQEEPCG8JOX8K5kymPCNyRvO98VbEGC409hbV8afGQAg5Qcrg_KyBVLxgMZIpJCb7v9IYYPfM0db3UVaFYoNDFPc3HrHPbLg70X4h-9ezvTi_9rj1Gdvs717iLk_c4Samr4zSaxDzQkzoqFSt3hOtz0TSkXwI/s1600/homemade-babes-035.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am3'>💋Adoro sentir seu corpo com a minha boca.🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgN5e7aR-eIw6ms3GZsHxFWjx3H4BWHyh_hnzUub1jWCcgUFiXYu-Vm0s26b-ufIeKkna2SznTo7cxajfiM6knK_QgHcjQk2atunJyV57yk-AV0kzWx3PPeTDO3ioShdGERvfqnkXSVMSP4wL5Q7PW-fQgdpmx_sYSFxNkRyuHkJDwOsfmvxKG4ftEXQRw/s1600/homemade-babes-036.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am4'>😛Isso, me pega forte, adoro quando você faz me sentir no paraíso!🍠</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done