//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiWTkJVqAFDJv2v7u5MW8fOBhdt_rJNkPc4rF_qHrstpFqHZBvefM_xofxEQgxFZpVz3UlicVYN2znGBxJbuU-HUOC3mzICq8gJB87OMzFK5MDOtV4zNTt7k_dCBHNThxtvOpozhoo2sfRP4wEKYJsCcHeeZZoErIe84YuUY1kWIsy0PXn4k0WZrwmch7U/s1600/homemade-babes-103.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>💋Adoro sentir o seu corpo com a minha boca.💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi8SMKzJjOBKnNBOwbLtTSYDRQfvEbeeAKrU4j7dfEPhG9DgJRFSY1V-mHw1jV8niRyS2PCljTJkbXBbR6yr3_d-jijHmQy7PeJZWla5juqVXZ98n95SeUJt5vWujXDy0gS4kt_LcSr4lQdZCjNkylJD8H0zMBRqY0lXNlIekWWy3YhVeOJWqxZxF6PsMI/s1600/homemade-babes-104.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>🍩Quero que me vire do avesso!🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjuCDm1EJeA1OPBvAPk96ZzXQyHeODKIQVPTujEWVpa2EKD-K1Ey6im4RPseofC-aTLuL2CEtMl8__AGXwTfYTDXx4HdscDf3q5CKgo3tbR6t9HzivJwGvuFsWocPby-tz4AMT1mNH7aJuFDZdAm57CfuSicas5lIZX_zD-GDAzxR3lX26gsQ95E1JCXYU/s1600/homemade-babes-105.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>🍆Hoje eu sou toda sua, faz comigo o que você quiser!💦</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done