//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjc4qmCjyJj52z5Z3bSiJ1gamg39yr9GF7y6aHIN-cRrAefs9VqBKVn7BZWqpqXZkZLkCZ5Y_Sn__rFQAS4anHcFeTT3HyRC842vgEFNSOBqZpaA_Z_1CITsGrpsqbEKAZVb4YwAWyb_tVaG01Clcd2T0UsH7mp9ha76ch5yuvaPv-w0FKWWq524lX-sQk/s1600/homemade-babes-193.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am3'>🍆Você não é cachaça, mas vou mamar até as pernas ficarem bambas.💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi1onilt3bIvs3x2AfNDOK1tSTGdSEfaUdbf6wO-LjxaoRe6JDxoAVd3QuzpPU4P2JymNitg3KlpVchwcRV_ofoekZhf8ihoxuTIrzNjIZE6HcFopCdaszIDPFZ9mEjpy5gVGKr8h3TP-bUtapt9emABGrxeu5JTJR58EptSLSnA7YHXZ8cbzQjl_S2FpA/s1600/homemade-babes-194.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am4'>👅Vontade de sentir a sua língua entre as minhas pernas.🦋</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjzRYKfPpY5reauDTzUJ_JmpFiHAmNNYn_FlF_G8_dCR1uRWydfFOkS6a4j_nnuOL_fqbMrzBfMTiiTsb6PX8vlk7zk_EA9YV-ZmIlvKXNFIUb9_Ux01-_iDvXRM0CBU0EFrfSRd8HqTgf0ZHwcHk8jB3zU5uctM4Wk-5ncH-68ZskV6k7SASrpJ_9kjsA/s1600/homemade-babes-195.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am5'>😛Quero você assim como a linha quer a agulha: chupa e mete.🍆</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done