//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgaD4TJWUqfuUgZmdC8qthxXcM33hrdRyk4pAs5cjY_hmm1j_Xl9M2YpOGxhLEcUDowaETCBeqaEP0dM1OSBBNuvZ3HkeYTv_diBmjIYaRauBaKKWv0xnjPWzh40Hc80egumYwQM7Ki9enISaD1wr6V5d9fc_8mrVzxQ4sT-rRFPHXGWbwPRUP_q2TpPfs/s1600/homemade-babes-073.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>💖Adoro quando você me pega nessa posição.🔥</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEheIf2q1qs4PdvDFHAWPJeJlHmVDv5nOkHiFadO77fc4_VW6MelwiSa9aHMjgSTCljGHKh3c2w_JVFI8qeWhYRv0jToJXaYeM8Kyag6DxNG3P0_mmMdkG8Zudp9KontPmgPy3IOhvCpBr3aMk57ados1Ap3XUcuvVLRhB4B23ZTim5Asgv4kflP6DXaVG4/s1600/homemade-babes-074.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🌺Delícia, assim, muito bom, gostoso…🍆</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg8gVXXB7hXB_wtLjl5kUOr9DpgX0-SK3GYcG1JrECUe9MAD7TuXUEKFnmIvcRTEsBiuKoNDi5QOIq_bFw3eS_MVtgUIyXoSoHbUiveIldl9WV77B50kqqptWXJ9PS3XxIgFrvFqOuEVo_dWui1NcwaRwB2GDEx7YO-VqNHfUFQe4jXyYCJ-sXyTIZi6zY/s1600/homemade-babes-075.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am1'>🦋Quero gozar com você.🐍</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done