//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjbSqjJTzK8jtEzvFpNIAuW7zcvOvIwCqc8OYkcRxpUqQg1FqYgjLxuLnm2nVTwboyKK6D7VLDwqT77lMJ9sLpepyrG_kKRvzhEwjIq2E7ojvzkHBUZ2uvcgjvQLQSEliV5K24SAnD-t3MPQQ1nGlJmWCL4zYvteyvON41Sb4lEv1VGb57hO9mabStr240/s1600/homemade-babes-076.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am2'>👅Adoro quando você me deixa assumir o controle.🍌</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhb1S8P6tPq70cj8XTj6Xc-doudZTdOvA2o7GiTFQIyB85hukdy4OTGV5GSecpoQoe5rK2fh_taqQo_8fd_CC23m54sfa6kAEgQEOOG2e7ORTn9R2OtJQNmmneZOD6WEVzB8tumUK9MZlIXj_BEJqkv94nS77PchcPtGInBoToraiEfMX2eU4gGrXDV2SI/s1600/homemade-babes-077.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am3'>💋Adoro sentir seu corpo com a minha boca.🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiKbFqD8aR-w3Zsud9TmoCnFeTUwh8nq9J4O0ahgcQWAY0NRGuct_hMS5Q6IodByXYj7UafsxFjZ-TvaFmp8fBryRMxxS-1ssD2v5O3dKtPuqF95AtjAsC9z9Na1yQh5TmeQpdQNPAgGl1DW94JLj5vYUha6B4jdM9TqS6UlkYnVTasYU43fm9wUJcnQD4/s1600/homemade-babes-078.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am4'>😛Isso, me pega forte, adoro quando você faz me sentir no paraíso!🍠</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done