//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEguwKO6qTxLoTUzNDKYwjO30Y7wwIX1IwsaobCzCwRn5fgWiRO1JYPEw6jwCbB62VRR9RO0__ZQhQuLP6MozJ0g9br3tbQNDvIKKABkjKR5GtPGy5iFjcps8izM-7g7pSZWRju0gOGz9FeYhWNBbJUNGpHpvCXwywmWGKngae6FH01BeEKqUVG-WBISeOk/s1600/homemade-babes-094.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>💞Muito fofo, mas vai me comer quando?🌹</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhni96HiQc0hi0OiEGXpxAX2apEMIPmUg66iCy5hH6kJ1g6BPx2a_ZTCguXKKo0G5HjYXWYcDtNj7Y56_GDE2nadBhh6hWxnENpDJGxkcc5LjlWnV_AwNuU3vFIKKzy_PGMg-zET7zOe4HcdcgpFBbmtwxkLDyBZAGMYfwOl4S58SMjqKmCvBzNaDcxJt8/s1600/homemade-babes-095.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>😛De boba, eu só tenho a mão.💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjomeWf279p6cj2PD_H2LSb6FLk3sHeyf6X3k5Tqn7m2_ASZ9iKhUoZKKA-LOwoyG8cVpI1zV2C0OqpMjp1i978_Efm37g9lPCp2LqIHbit9rH4uD-Yzij2NqlefbOLN0rdPgg74zgBf0k5asf8lHnfmYwqPH5PAfeFyCfOmgrr0y45iJcURKTJKfbkMiY/s1600/homemade-babes-096.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🐍Me beija, me morde e me faz perder o juízo.🤩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done