//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh8Tk0NC4TLttwk4o9InvRZmiNBiUaLfUMaWcSvBJzUvLUNRWThnGuF3YkzMcWVzGbegjGPvNZjhGeDlFlpIU4h-0BRLLB0_a37lVm3i7_IhTfSpEP1MY5_hln9ZV2ev2AQC6GE9uMok5-isdh8T4ZdrUuO_9qiEw75UYZkxGetmUszG9IWxvib7q8TSLQ/s1600/homemade-babes-166.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>🍆Preciso de você dentro de mim agora.🦋</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhO4r6r65Ox5MNIlPoXqhCa9fH7lJ-2yOvm4US_RUT2Avm1ZDryXgCJRBbjNhLO50-6l7_jRo9i2ZMDWltROZPpfL7IGGmU-J6ML-4MYToeDlZooY18SQmv4hadYBqcijCQBWW_h7vvMhgJwkQTBW26X1BQS2SMQFtmdNlsRs6Zt3bUkB0FciEQkdrMqfI/s1600/homemade-babes-167.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>🐍Adoro quando você me domina.🍩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjWs1nCIZ0n9wqhIbSmtcvfGqCsQvZQ6jn2XQjyQ0YVzrc1Fm1C_8ZR5dODQng0lUNxFh2SJTUEpspL_3ZMWpPa3EbxDvwk1koW382gbvIs8wpafxrIrO9qYFEZFkxktdJtxXMK7NQjGyWYb6WC-57gfOfR9NnUxv1ux5jV8KgdDf2QWaJqoXiZyiQqaH0/s1600/homemade-babes-168.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🐍Delícia, assim, muito bom, gostoso…🍩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done