//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi0Ubj6Rd5irFemv7qrgWA9na_Q5J9M8Z-rhcn9j6rytG2XeLOY4phkGIRg777Eb_Ew130NpRKDwYD5x8J0Wh8HWwg4wS3G64lg-YVaeLzqGjswLe1hgjftUFIX18K79fzttXKbccOLewl1nH_ERNmojApBL26si96zycaUC3ppREASMpmsA6-ypRULTlA/s1600/homemade-babes-211.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>💖Você me provoca, me excita e me deixa louca!🔥</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjUakAUkeiECencdvDPUUjxcLQNF2NSdlOmx9RtIon98d5Zz2cgifxZPA6zdEShsgEe69zjACfrxDGYh5DfhiuXX2qXZSQ5I37yZuIPP0DLqQE806cog9mmXXEs4i409QguR-ACfs4L7hRNlQX6v6LCNfkZb-msKZAgQnKMDUH-Y1E38MpM6BnfukdCVUo/s1600/homemade-babes-212.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🌺Há algo que eu preferia estar fazendo com você agora...🍆</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjsCR7tiO5BKZTMHDMAId1QN5iGof7tE2Idr50L2XEgNinQVjpkwGA58tHzLWnQzYwD6gXmLRqb1sUfO-RfF-0ANvjZKT_b43WfBY_D33GtEsSgOSH-SSYCpbMxtHrVehbFwWt1Oz0xTGjvb5j34hooASTXA5NzrMsr7O6mn1a3mSpNRuS_5QPNCyFKbso/s1600/homemade-babes-213.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am1'>🦋Me mata de prazer, antes que eu morra de tesão!🐍</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done