//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjQB7LfT0oiGmzdDyGw_ByUBrcDkWe_09ngUPmEGPNo5XZvuuzcR0X14XC_PT0kk9ZlS7BxonSycwIsysEml0yQSVLMegOZpSjWtanAKdO2vMJJ2TucuqYYcDDoJw3Sljk8YX17WTFy8lQ5N7qtCGdK2T5kLe2UKQ-SvSKIIgHceEtyobK4WFnyUat1er4/s1600/homemade-babes-172.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am2'>👅Eu e minha língua queremos saborear você sem pressa.🍌</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgKpO6-aGxeE7AicPtQg-it3eBixqDVuEr-0DiPVJetiq29zpy6YLpfrZdpZOCQXm10Dg3fbt5AxSBOWKJYnZOJz4piuyngEfD9RBf4wfVvMKF6vd_Dzjey-dFKMfRs_DADpT3wV7ua21a7BNEAkGmXM6AjCvNUP84xkW2xj4IQZ6pxEoId2nuDt2IyQ_U/s1600/homemade-babes-173.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am3'>💋O que você quer que eu faça com você hoje à noite?🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjnfsY0uYPg0kAB2HbOYVUOsy8LiGjludISYDKdPF7wtFoT2hk3Pq2mf4slGyFivvD7jnliEfHZyON_wrw9RlVm0C3kkZrbeZXrT3oI3s1jDV7Kg9YVnz70WDAwbdjgh2CEK2JT41TkFt1BJE66Q4xlkYcUHBc8l8CKTPTISxXBJPEA4TU8JfFNuWR56IU/s1600/homemade-babes-174.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am4'>😛Me leva pro teu quarto que eu te levo pro céu.🍠</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done