//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj5MxAtzthnT8xM6Qoib65vu5-jushhARJWjOpKlLA3tN8RGPLN1_T6KegggNhpIirr2joHzVEg4rc6JykLYjvQHsDhEaNZLkXm2JQ-8P-VShYEZeTCjKz7BOTmJBnDuqKs8dXwhUPzZohYzt9nhaQphds_19xh-Vjo9alvkcZtwZRjnnSflp2_OAnQEsA/s1600/homemade-babes-121.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am5'>😜Minha língua vai te fazer ver estrelas.🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjXP2aCC7h3-doD9YjVnaeflnAv2L8ZpovA_pUZnOFCCkDijGwOVzp-pZdxU1-2vtaElfvCbdhfIRv62kCPAohvrNG8bo8oufmkP5dG1h2jO70qBU8YnAwvE4JuuhB50nVSJlL_h5ZhOpIlG4i2oN2rXaTtrnkdTggsGfyKiCUCIxFvihHRQbQGi9x6880/s1600/homemade-babes-122.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🍆Eu amo o jeito como você me preenche.🦋</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgxs3WeUAB6-2kGSvGcki4YnMKWNo_VqPlhwLghF6Zf9bWkP85H1yUzmo3s2ARyzt6XqyCdiw68ECo8L67i9mRmTTHdIGrWVM4KSQV2n7DdjGbBaycc7N59aJiEMD2wT6u5XAdLseeZoDvQMk_V-v4faIemvkMUIIJNvydjc92MtTB8JSPNWD8lHGC3K7A/s1600/homemade-babes-123.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>🐍Me come gostoso, vai!🤩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done