//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjRTjPkItHUtRAlPkBy4lM0HaZWuEf-omkpic7UvoKO8fnEoV3SB6gzeBiLw1_7MKFPk5zSgurQUctXrVUPBknxISz30HigaIsZYIexMPegtCWMrDriW9pvTf4LhQETvuPiBWiUXWzpuU_uPQEGXI18cF6vxwuoiOpVdZRfWo19TBD_-JjVvQ7_JccD-44/s1600/homemade-babes-046.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am2'>👅Eu e minha língua queremos saborear você sem pressa.🍌</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiZS0xXgd05GNio4kQtyFJR9cdvNxQoE19jzyuu6W5_7MdutkIfhJuNP71Ew0p5rgMMvRUJfKk2SA9k7Z3llVOAwH_bJO5KyzPlqOVpJTQqiR3UbxO_vT2Y2ViOnd-j51wMM9sEBDXcwS4WAIyNMXHGNhGMgHEx4qXifagL2mwKYel7VON_E8_5J7gLXk0/s1600/homemade-babes-047.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am3'>💋O que você quer que eu faça com você hoje à noite?🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhcRkTI9NBjRM6f24ej447dTvAz-G8vSWB1Z4JhvIls8xgTWqc1y0Dkya8ev14QISTkpWFNOJ0UNwtZwBXwwppnNYOHa0Gs-Cj8UC5WAyP1UcNsduNJsceDMEgF3h1I9aasL0fFP87DBceQahjJ9SNu6jvMMPy_yu2nNmjkFQAPolmRO8_8JHWfZdtO1Y0/s1600/homemade-babes-048.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am4'>😛Me leva pro teu quarto que eu te levo pro céu.🍠</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done