//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgEie5PUX8mS3A5_xs6QtoALdmIA5fgcVDvtaWsY8tkw4lm0gFUZLn5mSaM54QJ7gYBVp2-J_hFAZYzh-QVgFyi586LMe7ZJD5Q6nWkzYMIAVtTW7ETr4rlQ6I-D1tN457wLmk0PHyNbj8TyxYfbDd7JsWONqTe2QHtKMmgTWtTRKLcvqZeO6xJ3GYdTd0/s1600/homemade-babes-082.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>🍆Preciso de você dentro de mim agora.🦋</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhLb5Mqh7ElJi92lxUT5zR3yQ1Ynyosrl-SpfmKLzPSRhAITxPstKRo1TSKunUo95jpUuv3on0Pda6Sd12y8dGN-J7ZC5Ifa-4BjxefbDKjjlIRxQB-Mod7drXMy4zOu8T6HEtUU1pBew83eV3JZ5-0u9I1G40BkM0wPHo0FqfFcROMx4mzb2sholZfei0/s1600/homemade-babes-083.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>🐍Adoro quando você me domina.🍩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh4zmbRtvs01u5CabDubrF7EOr47AJ0RXEXBHJLO_IJnxT2PKr5Tdoj2-Jk8LM13AJTHpqa52MMFF6kkPo4_iJ5aQlU1F3_TUdXvtLLsn3Dd-ULMAkhyJCQarv6sFaTuCv3eBCAWYWbGCmwI2GDyZLVOMFN0NeKb7gIdwRgOsGEtCl4QSDrfOr6wLTGEAI/s1600/homemade-babes-084.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🐍Delícia, assim, muito bom, gostoso…🍩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done