//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiNjf5IEL4Bkihd5xI46Y9lUQEAvTm8H1a8PebY_fBHwtRhIrTAkh4mT3qmlIjNKQNWKr5bzVfIqI2mZt82uIAIT0yVhf9mdQT6xqfM7_AJU9K02eowoRuyWxDkQ-oj-QhWWq34MGfknn2rXactKorDImSGJKlXMFWebJC-MHA2K_XH6FjzZDSwfrjBEhg/s1600/homemade-babes-112.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🍆Só para quando eu mandar.🚀</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiRWskUnjLu4yU2KCMGHNbDKTgDI7YTKM6cAHY2qjrZmMxAfA97x-IOw0ZphyxNRFbxNRlKefnMDikT88uHX_Ehu0txs2MOwAB7TEBnDD_apONdD2GOftm87yfR8eFZl89omiW-FQkClUbgSWqAPOiR8VRhB3XiCE2X4XVbg6fn03PtHF8ZSBquaqmZGaw/s1600/homemade-babes-113.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>🐍Eu amo o jeito como você me fode...💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh-uE8-ryHPffCtC4tC8DflenXfXyGqjlGraTLfAFLx5s25x-kwgHnbR3q2D8TP2e8nnogqtVDhlF1-nqLTXbleGY2HM-_zuXAtDlfvFktJ4LeHCs7ME7gMIqe7Qmt8Oneu76oi1H6nG8uC0jTqCecPFHwUsQ4R6GjdryCdvxaj5uz5HsZiU-Dz1aCGCto/s1600/homemade-babes-114.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>🍆Me come gostoso...vai!🌺</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done