//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg2aPsxhmNtb3gXKe_a485KJKM6qa01FC6_Rtd_UVTcTf6IdJ0Uojhn4ii2uN1MfHMiwfiGf_3giJmmSpOi3l1KQDajiVJmQ28GWeuihVS8IFiqs4ykgMypS_m8x3q5Dh3Fcu6I02BiLWDkQpXSMkr17P1LULSo8khA4k7vrhOMV4TyfKFrVa-WwdRLoRE/s1600/homemade-babes-205.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am5'>😜Minha língua vai te fazer ver estrelas.🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiOC7AGK89rYDzVFd9zfgSdS8rf3HTvxEQORw0zXqZfuZmb1m3r7koNeEDdSKGB4by1f4EgWdcLwuXcMJQLIG7tb3EbgG9PtPZ3BaFqC07ZzzFqR5OSDlQ9FAlzOKkOlAxLAoTmUgfg4ITxNnHon9GDDlst3dLFRcJUSbAEF1ViZBIniN5lt4K_LwLqQRw/s1600/homemade-babes-206.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🍆Eu amo o jeito como você me preenche.🦋</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjeTduB-A_6_tb1Dqkq_NEHmlo84HTZ_CcVH51xUjsLw5iOnF5RqHFm675WjZ5zstNYU604Ujbp4houJus4mvUnaTk1jlBoAiQNHHLxwV7QNi_EDQbUnSbVPPMYc1nQ8TDU-iKTRnC_vKPpMyGgKgq0oto_6GYX7YFe_9Jaj39bR6hsz5CTNVfJsUGfmw8/s1600/homemade-babes-207.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>🐍Me come gostoso, vai!🤩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done