//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj0M2rWp8vuQhF8gGX4VsxzqBn2KUUJCFTuEpR_PbJAobk_8PE7QUtZHS-S0doLyme2rqUCdErt5l6TiJebDo2kQx9LBRXzfSr859bLc_G-2-TbHA_SeUyslMtcdFxaxzgwug9tYcuCz5vlybkX4v4KDd-AFivo8Ol8vM1-Yun2jEQCvZKXFf4bmSJ3Vm8/s1600/homemade-babes-049.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am5'>😜Vem e perde o juízo comigo.🍯</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjuNVJza1wUjdXmc-RYFXJinLnSxdpaky7PWBbKG38jxe9PHiXWZPVKsWNVFilfUbKDNqnRnm8w3t6S2loHdd-c_U56hcS3-zeJg4BKRi10yiFDG4JpZ8_Xmh4TQDfhnhNTyFCf3r5zNXOq3D0Cdwjx-Kg7GcVrZ3-EynimqSPDKLv52MeaYQgXnBog3r4/s1600/homemade-babes-050.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🌭Prato do dia: eu!🍑</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiDP6mQ_UCmXzhdEbw8xG6tTTnNQEd4txLLEyr8fUjyMlm2BeA6283qwH6NCbA43aXPQ0YnxohfTn0ivgimL4XgDFfXkHP7-4bOGzkNv_m-KZqqoDIzPY3pnjqeRoACmYGjCqvzEX77ltkG4Odt_BX7Oj4nnQuUmln2J07kgooflvf3Jr-PkWzARkK1FDk/s1600/homemade-babes-051.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>👅Só de pensar em você, já fico toda molhada.🦋</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done