//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhUTBfA1D_1-1IM-fv9Nqiu5GNSHOvn8gYsHBsgkLNLSsj4vSkLdI-7Rd6MSbTFsJ2Ay2n_V48qdj1GOMyHjFTjaLAacheFu3SmYfyXsDYCaAWPv06J1W6BRpGMLJNHEaGsBUTbpLZ36Cba789RJuxaWyPoUs7np8wHd4X_i6-AtGhyphenhyphenDmfzU_4pCXWmS_U/s1600/homemade-babes-145.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>💋Adoro sentir o seu corpo com a minha boca.💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj4Eh3ERPVa1WXu0vSo79NOJ8iQnSX2AacC4dqTFLqKx5IXS2l8HlqbxwTvaPGELwZL5vIbug1Qj4-feQj4jfKnbqWOxIYHVOAmulOot4NPcxiZaH6bNVccdCy6noT-oEwImreoOCYgrhgrylEw-J-XKypaRXeHnxV-EWSQrMCMbO063exP-1P5CxSgtb8/s1600/homemade-babes-146.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>🍩Quero que me vire do avesso!🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiRi_115ypYgTN6DrA_NaGyoG01Og-QCMO2e4D_YVu05bKaNp7I9Iwbr82bmKl9z99fF2VxaWrVhbPp9pS_Zu2EBpvaqV07gLG1z-sONV55bR2mPFzjOupZoPzM3oEji5YcNfdel7tlmwZfkXbwXk0L4QWJL-PKqC0Xx9j_v-60H5U_WTnqCkl0as0WwhM/s1600/homemade-babes-147.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>🍆Hoje eu sou toda sua, faz comigo o que você quiser!💦</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done