//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjGj1wN8e66tnBCoSvZ4PHAjlD993D5C_xWfGHYJ_M3lfQdNTCemCsc0gLpNLO2sScAGorQwHcP4NWScyaedWM3U8qSg04yS0AO102lhpg-lVqNGkArvMwFFqqqnSEdR9Mrnez6ILLnK2LR2v9V3l9qngoEnRdOS_XJUobYS9CCUk1Gb0rUo_xJSSBoWkE/s1600/homemade-babes-196.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🍆Só para quando eu mandar.🚀</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjPDRSuh7cZPOuBjE2bV6a2fmB7xlOznb5D1WkMjc9YTCybgRAsjbVEbs3BjYd-sHjSj6m7oJZ9h2J15MFGBKDmnd8rQulVuKAneorrAnFaz4ILH-GO4DTtQh30YFFdm0slqfgb_RhOgiAxTq5MtMi47WWJ2XJAV3T8vHOU0dwT0sLwHgj_NwTLHvqSgfk/s1600/homemade-babes-197.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>🐍Eu amo o jeito como você me fode...💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhE0pYIcXzO8vhhQ4PNaY4LHzGCaJ65W1Q5qKk-neV2CNZvLA-nlmFP8kI8goCaKEzdsGm0pQsL5OUNateZ2S65e97zZEQ0ndd7wzYlQPG8JPEDLi2K_X4jHvYIuzLZpzLGzfiN_GrYDI-OtPk2KjwL9IlhQXMI72RClhhJ0ypFnxKyAfC8F1HtUpNO_rk/s1600/homemade-babes-198.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>🍆Me come gostoso...vai!🌺</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done