//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgY5QOQfpZkk580DKMV4Y1K8fjc12WAti9-RMoW0Q1a3aWtvaAoMXxEPXmv1fuTZ-ZOu6laYQ6HnNC5n72X9Odfm-q1dPMN4Oqu7Wo6mBopJfP1JQOXEE8l_lQ_eAeLKI6HgMQJSBjb_5joys4NKtTgNpW-8G4lUOgODih6pYVOH6FnE4kG7bDYBaODxAk/s1600/homemade-babes-181.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am1'>🚀Quero ver se hoje você vai dar conta de mim.🍒</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiIBytkMg0kt63BE96HFCJkVzxoxvh9CU-GtxBGIxUhr2PmHSN3EMgzDtUz6Hzx3iCZkyH8jggOGj2HFAhYxOCCskNH214YoZp6LA7XuTeXqaEKc1kS05fcUL6qVUCRFUAziCTgfJduhnqEZjZ2ZTh2GSjqy3z9tYBLJGiuso_8kVxElG1xqwNuluc6xa8/s1600/homemade-babes-182.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am2'>💋Adoro quando você me pega de jeito!🌽</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg4HkU0eaIq1m8Yx0MJlVgCVK1eIsiAJLN7T-QM6ldXE0PXcniTBaHlSytT4SGUxMe0bSgyBdg7-XV4zhFNi-zlrlQv_Vz9D-M7jKXRhYqoxuKMn8hyphenhyphenC_DzQ2LQPpJOCG7n9VepufIgUuzpQNt7hvn5HiK3LwISGlEiXuwoWORd4-6YBFYOjN2WzjKxPo8/s1600/homemade-babes-183.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am3'>🍌Você não é sorvete, mas estou louca para te chupar.💦</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done