//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiWC3N_hsFOdhhQOWsM0zxPptsPPK4nSkzyRkVhulxOopO-pF83000S0aIolzk_bIQ68JS-90VjU__LiMYAOMdcAd8M9dHQXXpNorLwmiAzv89NkA1NkkVLFUf8BKOGrmdizBQ3Us-GED3jDHfleyWlaOyynaRyYKWOTm4NhTCAMNvggdgjRdHc3_i7pKM/s1600/homemade-babes-148.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🥖Você é a minha falta de juízo!🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgzBZyZuRfIJZgdsN8QYeG5NffgoQ1pzUZX03013U8KBlYpOfVQtvKn9EeKX8lOXT41SX0Z62Omt6UHSTxZDlGVXVPmSTAN1U2ZI6i3qaHARgkFCvgxIWhQimMYF4MXy5Um3u-teTBGC6OG7YMXZ49mWdLgfJC3A4tnUmtMtRR_Dz-_IvMu6MWTQi1bqOg/s1600/homemade-babes-149.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am1'>🌽Vou realizar todas as suas fantasias...💣</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg8CcBgODtMKnrE_DEpIHRbaCZExi7fNX-6o2y0IpPfcEyCbplfJJk5jUk7w4jm8eMCV8TR_4QovmGfUgCEVsAUI20o-DEr6gzGnyo7fSLiou9K1-wA2vpvMAQ3Mpab9pU5C78veDUX9IQfFGi2M9unaQQIoYr_umEWecuIgFEkUp7QkMNzxtEjDDy-Qm8/s1600/homemade-babes-150.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am2'>😛Minha língua vai te fazer ver estrelas.🤩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done