//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj6XtoNBEbw4DTTL_AXUKRi-GQH6eqZi3pJKUjlA_Qzqrgl_8uOEdrR-H1ZJHCP7VAy6ColeQIcIV3c7280uuztjV0WoLpthl0OQWznMcZAeMQxkZVsTayWwy_DpzMiXiEzENFj003pp9Ds8QdsBOWx-obUBQo7M63D0mn8kjUyQJdXCf2SZpwYJJTqVng/s1600/homemade-babes-106.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🥖Você é a minha falta de juízo!🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiy8OYxg8U1GflshgcYHHJp6zRuEhjuWUXeJeBniw5rCyYzbaxToZY03PTFSNy9teyCvZ1sSa7IN6o9gRalm_brewoHs2Q-h2uKw_iuxU-lXj9j5wv7eQ50T0Kg6rB-vpyBlYSaw59Xscqswf-lHMbmUGAn_itxPYaYjWGci5gd5Ihcmxv7tNyGj1Yw4AI/s1600/homemade-babes-107.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am1'>🌽Vou realizar todas as suas fantasias...💣</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjqYQl8G3e1NOgFuB5nGU5kyHQnR6GHYbKlUsmP5HmW5Ih19AunjQuj-glI0IlcOMvSEyx0GlPjn-8da0iJqPuxpV1i4lZDsh9cl6-jc970gye7vfQp_S61wOwyOifuVNe1AOd-mGaIxHSr7lr10d6mVH-QMae-rNboIWqxivrtOjJMllZDZB0_QrdkNQ4/s1600/homemade-babes-108.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am2'>😛Minha língua vai te fazer ver estrelas.🤩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done