//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEibue-XWFz2mV3MTID3UzXKsr06MeP9CNKSSnLIPK3NFZrEiFtWIWn_fG8jNfH1ZkDmuWlehRdEDw8MR_uL4gqmzjVN0vd8lY9bu1wi3GKKXSCKjnBVA5rzkII7zp3SfJTxFWir7ohQCcf7sMApY_khobzVMErAlQ-Fmxg-nYaow3ceKIAFft3rOk2A9c4/s1600/homemade-babes-202.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am2'>👅Adoro quando você me deixa assumir o controle.🍌</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEixBtvc9KDOGCqoxchEFA1Wh3DXYeLnZLqC3d2nJgxthAw-hUhyhPkpcFMTLlSX10cU4GQOx453mQk_d0MiKTIXRkSoo6Qbh9_CByimjSakrH-TnJG85aWVFyWzMrHlUyYUPRlIDRGfBKr8KtXQx0pwOL7s0RaMsXNn-Mkj9NVxNg_kjMOlJN1v-_1t6Ps/s1600/homemade-babes-203.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am3'>💋Adoro sentir seu corpo com a minha boca.🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj4XfUbB-jALpbFq0AnJuqbpifw8EBOlacH9kUzexuoboaCIQNn4Tf4TDQ6BbgcDWxVg1mWgWlX3x4y9BoEDXBssfv6E7EBX2ArCnnTfaoOyWZDeJ_KuAn11q6p6WItzBHcset_amfnkj8l0Tj1eQvR8oBx-yy16JQmyiBOTkw4PWvjID9_M45qHvYbFHk/s1600/homemade-babes-204.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am4'>😛Isso, me pega forte, adoro quando você faz me sentir no paraíso!🍠</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done