//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDC02zMmDOm_IZKEExhJtC4sEEErFQayp0wqQ3hEiWWmw90DfDqZcx7szw2VVwefjEybaGu-fu3QzrUwXsA7leA5wEptLlbByBLQaZfgtuzBTIEffDzKeoolDMY_8txZiYB2FNllBT9aWPpLKzuJGOL6WCkInCi2fwtBFWVbcV6fL5UeVpvg-RftV8jxs/s1600/homemade-babes-061.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>💋Adoro sentir o seu corpo com a minha boca.💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgjwO4-hRgv_wgVH8u5AwvH-uvqj4-Bpq4qRatdrjXS_iSqZoAfF_rfp-CUfUVPogzygberv8D5p_KfCWH3TOdtmg7z5slR2FUnTVrE_3E1ZKouyDxw1NfCtJEOJJ9Y8_DJE-uFeXslglLP8JLDkXiKttQl8Bo9zZWXuso2ATGEB8wmUea_aO4Ky3XAxtU/s1600/homemade-babes-062.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>🍩Quero que me vire do avesso!🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjKqAj1zvJ3JagrTOn05l8invb2MZg91FvyMZ5WXTL2j6f3a6Y_-6jSK7_evdLK-dKjMg7Bw1-2AQZIJ1yObBEvg06nPe2DudPS87cT2IFilYEQb9okM117qBy_AF1UmYdZft7lyY6ZIe12eZMnyBR3jN_Ut7N1fy2FlYeEV2C0DOuOBP7F6o_M1Q4l0TI/s1600/homemade-babes-063.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>🍆Hoje eu sou toda sua, faz comigo o que você quiser!💦</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done