//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDJsGo-PyrBb0bL4J3gRG8uPbo311sro99ikOPwfAnR_p3M3vdCaBGEqyFYED_Gs5Mio2lDAQabkCfIxyjlWXTBbZ4Rascydo5n7U86UPAtnZcMaroZ0-gfo6PaVXyygqv0IIDGTN68p7hZmsZS2_LQPD45fNq33VoWhyRorABmWOxSCeQ-CbYjUsAcAI/s1600/homemade-babes-109.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am3'>🍆Você não é cachaça, mas vou mamar até as pernas ficarem bambas.💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjvy4CB_uX_pjHZ3DCKUTPZRZymW-_L0CrhXM2dG0nd9x_ogmdj5hev_lEbYModfw87VVNHxIU2NUUdc1AECuKhLV2sOFmslSUfAZOf4Z1Kb44uX4oRLB_Yde48jyQqXBIU_VwQthQnoHCugyGg-fkEo8FkuiShN8L_tIp_CLXURbEet6PhQFd1AD6-OS4/s1600/homemade-babes-110.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am4'>👅Vontade de sentir a sua língua entre as minhas pernas.🦋</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhu-9Tuib1WARiyvfmGaAnICrnF0caiddrDco6Z8uYdKgv1DE24GSU5RT_1KxPGykO4b76_1ttWPBfTRePSBXwxDNPe3JT9Vhi2Ds8N16z0vPTEzuGuf41iIQHJXQiBUEcB0FTbmXPdmApK7Pob39hiRHQ9nV-reKcvJGZ6zeoJd8u9TUq9OhRGSS1KltU/s1600/homemade-babes-111.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am5'>😛Quero você assim como a linha quer a agulha: chupa e mete.🍆</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done