//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj3UcrcCYY0sbounK_De_LOKJRziEllE8os3MJ9VIEIM-ihJmZobbwxxjTRd6tqdOVs7jucOOeREgtLk44xWNFvF2YTqTSiobCAGFhq7QCAE9AryXgY6h2znRp35IlaVoXjQ8DctX38g6TaScakv8J8L3uhGXIh3hyeLu2xx6TDRebcOi8ZlhSyxNyTeIY/s1600/homemade-babes-136.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>💞Muito fofo, mas vai me comer quando?🌹</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgrOfuJN2QiE7dfByZ5p6G1XTj2ZIWJIiu6QDCRODttsk7jg_74vTNvKRoCC7P1FLk-dnf-tEcAcgATZQy6Pj8WKXnB7ETNO_0c00X8R0GkLtI7dbZaYYf0DJEefcVw_P-dCfhBtNC3vRm3yuXBvLPTz0anXN-who9bAFtT_Z9reGEUohasVWZBBuFbzkM/s1600/homemade-babes-137.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>😛De boba, eu só tenho a mão.💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhBr-WxVQdAuTrYfZeCEr3qwvIjEAfEAvdBZ-GL6ElgjFvqRk85buM0RiLFftrWSoi5-sGvaBb4vC7CIKnDFkn5MzhTjAB7CKWHLhC7Lb_IGTsml1balnItC7sZFiKTMLrRz18gNU61fH5iHpRvhxJx4j5GU68mlxgSUeCIfKgMeN8xUWHAkyW3G7imuSQ/s1600/homemade-babes-138.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🐍Me beija, me morde e me faz perder o juízo.🤩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done