//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjFI_NMVW3dzxJa7Ei77zTwBacsFJ3N_cdzEgzy-WTGGoR2AkkFzeMonnk4TvlPWNCC6v5wBy5A14SHr4sMp8__7ptxUcxJDWkJLi5U50l4OY4tMNUKtw8n143maIc5-8t1RUchyphenhypheneSkI2KVF_-lRw0XPDDkudZxMhp0ds68EyosjRkBux0gSInNEKbWHNM/s1600/homemade-babes-010.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>💞Muito fofo, mas vai me comer quando?🌹</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgenffenh7xDo9mu7pqVFs5zK3gyfiHE3iM8GTSsUD1RBAZtyOKpaKSuf-7PK8y0x05M9CXVRZo-wIlPYxq6Tv9RFiJSimiN8bNmfnTVKhIn3OE5xlMlee4j_d3VAS8mNXDOuBCJng8XGyBWuGpfc6u47bcFHlghDF9HQp1jjOKij0PaKXeLffzjGa1NvM/s1600/homemade-babes-011.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>😛De boba, eu só tenho a mão.💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhpoZ2DNKyc6_lXX0ism-pM1UN8ooojFcV8VyI6w5snyey_yxEz9vy7m3CgCK_dnI6FmC7vzcR7rhJ7R7xvp3rp7MAtNtHMKMbDtjopctzXnf1UJDXrzddgbEXR-9DDaVzGdXGnDmVtVVrB_yL05f0O6DXBxsFSe37UzzqpC4if5ZNPIhAgQc89wqIDcgM/s1600/homemade-babes-012.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🐍Me beija, me morde e me faz perder o juízo.🤩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done