//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhlJm7I7gz1W6oS28OraR8-2YeqFwMNRvEAXWCFFxqG0MlvmI81sv6MtZmgTlrLYuMNQCK2L8FLboOdPwE4a-mvSj97h1YZBga9brOp3x4LoUEUSVUm5zyFPD8FraefdWQ6GWyCEI-6uC0ymJNnHeu2cGHt6ByTbiFpZylXGaxQ8S6x8mxSYfb3Nf2UAnM/s1600/homemade-babes-163.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am5'>😜Minha língua vai te fazer ver estrelas.🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjB8tAxJaxLn8LIMRwq39AT-9ReDaj9pBgJ6Jx6d3n_k3VC31r_kqetKKNHUCWUDJbpSvRhbVTUp3EIptrg63gtQJslyNxZqD7hZsl410EklQEvBWRrAAlYFRM-tTPQxJcIIkRk4CKrSKDahQIwxCFuD768EcERPgG5fAIYCWuR8tjXEFXff4C5F0wzmuY/s1600/homemade-babes-164.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🍆Eu amo o jeito como você me preenche.🦋</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj1jTrNul9jc6sem_7LlAvG3i3Df0KAPJHdAw-vDoxx1LrAzXISjZxcdWruDzi6vdRDOgk1vxvPA0HrYsIzcpiOcegb24_lyG-jspZ3fIeYU1eq758lKTA38kqXHdFz2Uxs3gsPq0d8NswrQW6V2BHMBAxPVEYeZpS9e2mpy-36llzLWbBkIgFa9NTX5A0/s1600/homemade-babes-165.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>🐍Me come gostoso, vai!🤩</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done