//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgqCjYlcXlWHP7XqNmChvb-58PXE1JgfQI6MIXYsoHWdVH3PrnRJB-OQw_8jgiySS2gjEJw3PWNZ3ZsWVLXFgcwCZXL3j8veGL-uipiAZ_EGzm6lCsWGpGKrZ1A7Rn4eVkNddiEHV_jjY8slBr8HLqE2BTVdjZGOnlEH_udTeeWLhxlbZRnAgtPDIkhHl4/s1600/homemade-babes-055.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am1'>🚀Quero ver se hoje você vai dar conta de mim.🍒</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhWsJCS0flwf3HUkgYLBd9-9L3MnSR_EyWZo98cLD9F1bj1AOgoN97vlipUu8J-h4IfxYAjabpveZ7RAixjy5myQZd3Z-Yr3I-UZwM1K0T7ABl8UIjcTbEl8IDTcWMKv9DkK71eIDBt9Pwi1E-30rjviYsQ9275eRrdadlqlCB42iHFwv7biXg_9Qst3EE/s1600/homemade-babes-056.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am2'>💋Adoro quando você me pega de jeito!🌽</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Shopee'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj_4wo2TR98QDLRLgFMZhSDZyb5gWg8CoApC1SY-EPuHR3zAT5VMe2B9Z_kNKYkXKJY1IAjPhGFJkdeB6pgo7kIkxlaKWx7tMlsMVRdkz59DMON3lGUHLrKpDwu1dk8LlM94CFaQYEyKhhvdyphyLY0ey9Ohh8bz_ddIUCObTAuOexvD3Dpzeft0LwqDqc/s1600/homemade-babes-057.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am3'>🍌Você não é sorvete, mas estou louca para te chupar.💦</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done