//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgK5f9DM50EuMWf8jImCqa58uIYudKFGS1m464kCA4pMEfDeZPbN4F8laUZ9u5DElFxOawKarL_nud2rSUuvYn7pK9wkJJA1U4LBiYdAb5zxsPKHZwvnQiK-EQQhTE_LEzmZN5n33M4fn_1TUl775sWqKutTxhPlW3WdgZKTw5CKbuKSqrmcSUq8AMKi3g/s1600/homemade-babes-019.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>💋Adoro sentir o seu corpo com a minha boca.💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgPSlypR2ztmHELZGdUwFFvf78V40ZWzS_7CQwEPl8gLT-hOr1X5r-fUzw7Lo8-QyO4yh8qzxF3V8g8reEAzCZpLw_9XTbFtft8huyixTTDjA9NtIP6oM8w4V6ozpTZgjcgmFqu032Sqrh5wk-Gg5jGK-R1LGbNkI-heQfGjRkHJHlAJ2FH674Z2UKDeC8/s1600/homemade-babes-020.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>🍩Quero que me vire do avesso!🤩</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj2HGn67I5-OxRMtSgL0TIEAdYg2WySlZvYX1bRErId69mmr3U4a8sMbVUikSvm5hvLO8wgxkGLaKroP_YGCC4VaEjP_lxlSBBP91CU8Af98YvtKYF-ZcE5FNMQ1YdX55QRL1D6S08SIIJJqal2eoSWAUcDgvPD0D4BseCN2Td1DhJPAOqBZC97eJG1TEc/s1600/homemade-babes-021.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>🍆Hoje eu sou toda sua, faz comigo o que você quiser!💦</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done