//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiDYxdrn2DRVaxOLxbth_P6C7GtUZZWjcEtFCstxTQZ8cJ3ObgOmqidUHhrKZh8LPrXKf7IwKjFX2_8QFfnUYvzDBApg7ii642iukKQp6YqF81mMScoL7JL6gfk8Xlul_Ie5ZGuCRpmnQBo5bh1oOFV6X5kLDZwO32po1x5dngFQXrfXWvH0_7u79o7_pM/s1600/homemade-babes-028.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🍆Só para quando eu mandar.🚀</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjfQZn60fF8BKjYoKKYUbKFfRiiiozhMJtMzXqLfa29qITanUFBO7VVo3lkY1CWKk2hak8W-NHLwGhKdlfe70GiJ9qJSkC4PAqNjVGffXFzMCLg5842HHH2wjBUiz8aYnwd6AtdX60QFu4gzeGhGVNEvtpkYr72sH_CxiPQWatMTVSovT8kHAWYa6w2-uQ/s1600/homemade-babes-029.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>🐍Eu amo o jeito como você me fode...💦</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh4IgvlgtzzjMB5t1vgGnXlGbiKsJ3w9vrgtZTz7dceEHn1GIRjSEmY4JIFDuRF8XH-qnK-WUB8uECqNmZ6jG10JfudgSid7aqAXmo-VL5SBRKBVvWw9G1o_n37cOXXBKyEjQUAqgYbxekD79mbC5ouse28bcieVWFDxoHcNQKgOzji7hZNF_kpW92mwUo/s1600/homemade-babes-030.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am8'>🍆Me come gostoso...vai!🌺</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done