//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjLCmHv5dP7XL-lTEHswDL3dM_mXZ_i2UFvJq7CWfXAFnNNCB6INLOp9Vlxg-uxVs-Zjsx_5VCjl4i2Hmp95Jakmb9wv3ofOaiMq_i8YtSdz12vfk_ny920N2sOQixUMTjBi6XBZydAyTU49BUX8X89ohlhRC2rMbwNRtTWUfmTzcx3tToSpWlKNylNVEY/s1600/homemade-babes-007.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am5'>😜Vem e perde o juízo comigo.🍯</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjTnXkK8riCgAOY_4Kz_AdosJJptlwRUwSO_AlHp04TwSHkd2sTwj3KDTlhXH-SuV5rQePprd7sGJaEnCRLSRXJ4KhaRQJpoFciSymbo4CWd94HkhdUOrwqPuLnp6dv_MghzNckeWtK01yhPX89jEATQIW8L4msh3UySJMlMq7q7yoHsTyHLV1A-KsHeoI/s1600/homemade-babes-008.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am6'>🌭Prato do dia: eu!🍑</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiCabsLa55gfFcJHYzXSLql5dhUuW_TbYxg7ZQIo7XfHjhrxULSzx1xlewejaMZnmvLgq-Dse4bvVqQDUKTT4XKEyIZJr8JsOCyG-Z02dNmyPDuQd5FJLwfiuoLoZNs9qlFffQa9WUCwXIKDngTbtRzQ6RJ0uqkotH0sal1BS6scbj3GtIVF7JdCqztogg/s1600/homemade-babes-009.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am7'>👅Só de pensar em você, já fico toda molhada.🦋</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done