//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjyjTFBUCjGByxy4sT7SJAv9Tf4C3uxHQI7dCY55S1ODFyCNjVbI2M_U6uSzokTplkCbMZtF-wmPU_LHOssQXPrVIoNUwwdkVCpR3K-MVQ15PO3VVBISJYb6ERqejALiKr42kVrdoENCUL2YnICw6jDsCowcYJFmHNXrCgMkEfezmnqTxx_Zup3Fcjpqsk/s1600/homemade-babes-157.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am'>💖Adoro quando você me pega nessa posição.🔥</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg_YJf8GuCnTH-UW6g9WhetB5hKyNR8T2xurCExnz_FJd-csCqhG6Ka_JUvCrAq6qNVVu9w7w33-aL2fVu5GUz2VIl22D3nJNkka0l3lu8YYuyFxu5yKNbpRY_hNB7XOaZ7fBGkeSQK-zRhBO-KKBJojX2MSC5lBp6OguciMQeWEo4hvpNrqGECs6dDgaU/s1600/homemade-babes-158.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am0'>🌺Delícia, assim, muito bom, gostoso…🍆</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://amzn.to/42xN8s3' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhXMLsZnpHlzzOvmke0EMDRHNFhhtx1YhWO9yf1wtHiMDQtA_h4k6NpOqzo85tUA91LzmN0px4OM2m1prNEVogs2mo8YVkWlEksEpazZZQ44IqBe5HQ49FTjc9anTGTmhmRqRL3KYhEWBKcB9nKZewHvgYejOv5q2M8WmxbBni2ygtW8d9-uICjz-DyCSE/s1600/homemade-babes-159.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am1'>🦋Quero gozar com você.🐍</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done