//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgtPdUmnPWBj9kH6HKx0cLsgPw6cQgzGkXxIhmk-Ud2Gm_ErWF_zv7VwWWH-entt1co1dGfCvjcvh6xCBeVKMqMOJjlmmVHoF7m_FBC_wfCFcBvhRAMehuqf_nCAtQjY2Gcrgd2xqT7Zd6IOCHL8NUQH0i8KZSRWf99Dsajxax3nTQWzLsDfx_F-a-GMCU/s1600/homemade-babes-139.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am1'>🚀Quero ver se hoje você vai dar conta de mim.🍒</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgMUQg_66SmV4VSWLqm9fnj8s-rMkUJM9GC5avQcRjCB_cvYeXroowjtqoVFANUWR_GeoyKuZbR4HNZ9TjXrgaDmQLck1Pguf5df4smraSax64X1AQm4DYx4qw1PDBEnHfoeiFddZ55fpC41FsaDzdj1Si461Nyp4Uq7I6vdBr8MHlGjqHvU8boD-EfYnI/s1600/homemade-babes-140.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am2'>💋Adoro quando você me pega de jeito!🌽</span></div></center></a></p>";
images[0] = "<p><a target='_blank' href='https://s.shopee.com.br/9pR9GLzVpC' title='Produtos Eroticos Na Amazon'><img border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhlsM117xFr_TpJGdOQGaVWN0Qr3QV90tHpkQt3RvU6bk4VVzK-HRFlbgzup8ou0SDuAOXZ_750yB5vbFRBmVs3dK38-5BiOIHpYSH14sPCCfPVXVh1_4d6ypzY1b9bAt2p8aesdPI3UyXFBAYnoN6IhdPiNXragpdRZW3BXcUAuT3AiVbsRhAgkpHE3kA/s1600/homemade-babes-141.webp' width='100%' height='auto'><center><div style='margin-top:15px;'><span class='am3'>🍌Você não é sorvete, mas estou louca para te chupar.💦</span></div></center></a></p>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done