//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<a target='_blank' href='https://shope.ee/3VDNHWRl8C' class='screenshot' rel='https://s8d5.turboimg.net/t1/106257242_shopee_04.jpg'>O erotismo é o grande triângulo entre o homem, a mulher e Deus!><img class='top'  border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjv3skitmaUz-m1REmpqoXSmmUxnwY15sa_-K2XC98hG7iP34pWQZGR0v1M4AUGpaMSlBt2SXEua7j7wau95iCAzpXl8VpW2fMcQLlo6jjS_trhLTWLs8J-eQHCieBp_9Yjlo1P8MSkAXe4ew0oJqGRNFK4qTsFdpySf3uYsh1wj5MpoRZouprHbZFs4VI/s1024/slut-teens-004.jpg' width='100%' height='auto'></a>";
images[1] = "<a target='_blank' href='https://shope.ee/3VDNHWRl8C' class='screenshot' rel='https://s8d5.turboimg.net/t1/106257243_shopee_05.jpg'>Realizando fantasias com Produtos Eroticos da Shopee!><img class='top'  border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiUxYqjRTpPpTlzZ_jCi0yw4J_Ga87N2WBYTGjRCxZfQPGkJd2fbqWSVQ2PzhB1GceTfPzk6CByGt5Qyb9U1AAvTKHnMiRiQgwYqogY22IN5LjvUeilsZzX19L_3c1rRGTbJynsaggOr5aJhmRd1S3uyfIg25EwPsSJkqc9S7R1wWd2Bxk4fq1HR6HV6aY/s1024/slut-teens-005.jpg' width='100%' height='auto'></a>";
images[2] = "<a target='_blank' href='https://shope.ee/3VDNHWRl8C' class='screenshot' rel='https://s8d5.turboimg.net/t1/106257244_shopee_06.jpg'>Realizando fantasias com Produtos Eroticos da Shopee!><img class='top'  border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh2ypKjiHkHnrLRua6v-AQxhPSF8yOq1jI9gmcY2ejj-N6ifCMHSb_hYN5UcmSzbOc6WkPNXvD75Z2P1EauZNLejgaa_TcdEdOL7di3RjS7toyg73AxLe1FecyDbWaqR7rLXHJxpxXjZR8sImF0OLpozixjQM0Bv9uG9qR5OGC4JIaARpXDuGoFlp0gapM/s1024/slut-teens-006.jpg' width='100%' height='auto'>O erotismo é uma das bases do conhecimento de nós próprios, tão indispensável como a poesia!</a>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done