//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<a target='_blank' href='https://shope.ee/3VDNHWRl8C' class='screenshot' rel='https://s8d5.turboimg.net/t1/106257248_shopee_10.jpg'><img class='top'  border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhbaKEuOlddQTYayYFehmAyHvUkq87ulopbGN_3BdlRG-YVysS7O-dBgSTDM_vQvMXg-xbb35cdEZrLIB8P4go-_me_l1MaFBe5YZaY0q7BPEPrpOt3vfaY9FiyHKDCvC-un08C7QiDoC_1yPrpIDSLLSHIKQc6Z9X1HBGw1yqz0Uygjvt-QUJcS0wT-AI/s1024/slut-teens-010.jpg' width='100%' height='auto'>Metade do mundo não consegue compreender os prazeres na outra metade!</a>";
images[1] = "<a target='_blank' href='https://shope.ee/3VDNHWRl8C' class='screenshot' rel='https://s8d5.turboimg.net/t1/106257249_shopee_11.jpg'>Viva novos momentos com Produtos Eroticos da Shopee!<img class='top'  border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjR_Aeq5Lg8caFm2Z6jVdyYMP5XOLpMojUuOMwR0Z8b6TPXhWJVccXFKyIwxsRh4QskKXJtwRDM_QxjCt-YIDhqpSVgof5FpEv3IIWsOwa2QaaczYB0azvYYGGQIdh7PqcJdeNOrlqNV0z-_zIwaAujQbJm_BaB-jU1mtnNzGePYMOFPVuk34dsoo1wrDg/s1024/slut-teens-011.jpg' width='100%' height='auto'></a>";
images[2] = "<a target='_blank' href='https://shope.ee/3VDNHWRl8C' class='screenshot' rel='https://s8d5.turboimg.net/t1/106257250_shopee_12.jpg'><img class='top'  border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgVG1_R71Ic0Fz9HqLA9s-z-a-egvHBzMrlQV0UCMTZc1xtwHHyP5kdC2ozo3lzOLGCdsJiycKVpLTpsNotRvNWgSWEaf89sZK5ZneL5RzeeDH1w8fLNMUdG8R6YLCVMN8Chqg7FLCvesAEhWxtapXw-_8WQiC4segZxtb405X76aNtC3ADMSAhqZxONoE/s1024/slut-teens-012.jpg' width='100%' height='auto'>O amor é o romance do coração: a sua história é o prazer!</a>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done