//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;
images[0] = "<a target='_blank' href='https://shope.ee/3VDNHWRl8C' class='screenshot' rel='https://s8d5.turboimg.net/t1/106257251_shopee_13.jpg'>Aproveite cada sensação que o prazer pode lher proporcionar!<img class='top'  border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEii9x-Fbz2zbPHKkgcWpRxpuv8X1zO1ONVH6gAEFBv5LQdkgLRA_alQvFVRPwJj4cW81hBqwypsR_kRYXrycEdIM5unaan6nbatsBhoLGvNtXEy_m6-oDOHeAITbJXCqvsQY5lClOW7JGdN8sVYmofguwSZAMYKyJHr69BtX0HRQgKSz5ypUVdKJAMvz60/s1024/slut-teens-013.jpg' width='100%' height='auto'></a>";
images[1] = "<a target='_blank' href='https://shope.ee/3VDNHWRl8C' class='screenshot' rel='https://s8d5.turboimg.net/t1/106257253_shopee_14.jpg'>Todo prazer é erótico!<img class='top'  border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgqnqRJVrB9baq-4FLxAKJoFWf082s_M_9NNrYltSBsScYWx8aQiygAJtY-VW2e1c5rxkGSyqqKxsEl1z8RZUR9I7pxWRpHP-OBCmSn52HIn3IdVSBuoI3bawpnUsGUaBWcfXCd5JxoRMnh1KrR3L0lksHe3l0UcLLEqlRiWmiunE8jiM0P85QH9FrYF58/s1024/slut-teens-014.jpg' width='100%' height='auto'></a>";
images[2] = "<a target='_blank' href='https://shope.ee/3VDNHWRl8C' class='screenshot' rel='https://s8d5.turboimg.net/t1/106257255_shopee_15.jpg'><img class='top'  border='0' src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjCnwTB1vMG6OPbW2lUIMpG5RivT-2ZWSKZm5LLg1zbg7NGmdFquZsSqHDW48JTa_5cHovwLn3Pil4DLl3tXOAJyV_-KO66dhmpZNAlRCAYgUJw-7dTIwo7OoQ2meK8ZuhehkjP7flnIl-0Vn_QiIqiY3eMGUz-6H3QgaHkUXldwONsLx7D6gKbh_kwoGA/s1024/slut-teens-015.jpg' width='100%' height='auto'>Os produtos eroticos te ajudam a se descobrir e a descobrir o prazer do outro!</a>";
index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done